function require(str)
end

require "color"
require "deferred_rendering"
require "drag_context"
require "event"
require "id_item_cache"
require "interactions"
require "point"
require "queue"
require "rect"
require "stack"
require "drag_select"
require "mousemove_editregion"
require "mask_edit"
require "time_scrubber"
require "tabbed_toolbar"

require "ui_area"
require "ui_autoplacer"
require "ui_button"
require "ui_checkbox"
require "ui_itunesbox"
require "ui_editbox"
require "ui_font"
require "ui_preferences"
require "ui_scrollarea"
require "ui_scrollbar"
require "ui_slider"
require "ui_splitter"
require "ui_table"
require "ui_tabview"
require "ui_tooltips"

require "modal_choice"
require "console"
require "ipad_dialog"

