#define LSS_SECURITY_KEY	"1234abcd5678efgh"
#define CLIENT_VERSION		"ext_180923"
#define APP_TITLE			"MorpHeuS"				// APP_TITLE binary dosyasýndan yüklenir;

#define DEFAULT_DEFINE_YMIR									// Ymir Entertainment tarafýndan resmi olarak tanýmlanmýþ temel sistemlerin (enerji, kostüm, ejderha ruhu, yeni ekipman) tek bir bayrakla toplu olarak etkinleþtirilmesini saðlar;	"UserInterface; Locale_inc.h"
#ifdef DEFAULT_DEFINE_YMIR
#define LOCALE_SERVICE_EUROPE						// Oyunun Avrupa bölgesi için yapýlandýrýlmýþ sunucu hizmetine taþýndýðýný belirtir; dil, para birimi ve bölge kýsýtlamalarý buna göre ayarlanýr;
#define ENABLE_ENERGY_SYSTEM						// Karakterin çeþitli eylemlerle (görev, savaþ vb.) enerji toplayýp bu enerjiyi buff veya bonus almak için harcayabildiði resmi Metin2 enerji sistemini etkinleþtirir;	"UserInterface; PythonApplicationModule.cpp"
#define ENABLE_COSTUME_SYSTEM						// Karakterin görünümünü deðiþtirirken istatistiklerini koruyan resmi kostüm sistemi; ayrý kostüm slotlarý ve kostüm efektleri içerir;	"UserInterface; GameType.h, PythonApplicationModule.cpp, PythonItemModule.cpp, PythonPlayerModule.cpp"
#define ENABLE_DRAGON_SOUL_SYSTEM					// Karakterin güçlü pasif bonuslar elde etmek için ejderha ruhlarýný aktive edebildiði resmi Dragon Soul (Ejderha Ruhu) sistemini etkinleþtirir;	"UserInterface; PythonApplicationModule.cpp"
#define ENABLE_NEW_EQUIPMENT_SYSTEM					// Kemer slotu gibi ek ekipman alanlarý sunan resmi yeni ekipman sistemini (belt inventory) etkinleþtirir;	"UserInterface; GameType.h, PythonApplicationModule.cpp, PythonItemModule.cpp, PythonPlayer.cpp, PythonPlayer.h, PythonPlayerModule.cpp"
#endif

#define ENABLE_FOG_FIX										// Resmi 16.2 sürümünde gelen, oyun içi sisin dinamik olarak açýlýp kapatýlabilmesini ve mesafeye göre doðru þekilde hesaplanmasýný saðlayan grafik düzeltmesi;	"GameLib; MapManager.cpp, MapManager.h, MapType.h", "UserInterface; PythonApplicationModule.cpp, PythonBackgroundModule.cpp, PythonSystem.cpp, PythonSystem.h, PythonSystemModule.cpp"
#define ENABLE_ENB_MODE										// ENBSeries tabanlý post-processing (gölgeleme, bloom, HDR vb.) efektlerini destekleyen HD grafik modunu etkinleþtirir; geliþmiþ görsel kalite sunar;	"UserInterface; PythonApplicationModule.cpp, PythonSystem.cpp, PythonSystem.h, PythonSystemModule.cpp"
#define ENABLE_ANTI_EXP										// Oyuncunun isteði doðrultusunda deneyim kazanýmýný tamamen devre dýþý býrakmasýna olanak tanýyan Anti-EXP sistemini etkinleþtirir; seviye kilitleme amacýyla kullanýlýr;	"UserInterface; Packet.h, PythonApplicationModule.cpp, PythonNetworkStreamPhaseGame.cpp", "Server/common; tables.h", "Server/db; ClientManagerPlayer.cpp", "Server/game; char_battle.cpp, char.cpp, char.h, cmd_general.cpp, cmd.cpp, input_login.cpp, packet.h"
#define ENABLE_MOB_SCALE									// Canavar modellerinin boyutunu sunucu tarafýndan gelen oran bilgisine göre istemci üzerinde dinamik olarak ölçeklendiren sistemi etkinleþtirir; görsel çeþitlilik saðlar;	"UserInterface; InstanceBase.cpp, PythonApplication.cpp, PythonNonPlayer.cpp, PythonNonPlayer.h"
#define ENABLE_LEVEL_INT									// Karakter seviyesinin 1 byte (max 255) yerine 4 byte int türünde saklanmasýný saðlar; 300+ seviye desteði sunar;	"UserInterface; Packet.h, PythonGuild.h", "Server/common; length.h, tables.h", "Server/db; ClientManager.cpp, ClientManager.h, ClientManagerPlayer.cpp", "Server/game; char_battle.cpp, char.cpp, char.h, config.h, constants.cpp, guild.cpp, guild.h, locale_service.cpp, log.cpp, log.h, party.cpp, party.h"
#define ENABLE_GOLD_LIMIT									// Yang para biriminin maksimum taþýma limitini varsayýlan 2 milyardan 20 milyara (20kkk) yükselterek ekonomiyi daha geniþ tutmayý saðlar;	"ScriptLib; PythonUtils.cpp, PythonUtils.h", "UserInterface; AbstractPlayer.h, GameType.h, Packet.h, PythonAcce.cpp, PythonAcce.h, PythonApplicationModule.cpp, PythonExchange.cpp, PythonExchange.h, PythonExchangeModule.cpp, PythonItemModule.cpp, PythonNetworkStream.h, PythonNetworkStreamModule.cpp, PythonNetworkStreamPhaseGame.cpp, PythonPlayer.cpp, PythonPlayer.h, PythonPlayerModule.cpp, PythonShop.cpp, PythonShop.h", "Server/common; length.h, tables.h", "Server/db; ClientManagerPlayer.cpp, MoneyLog.cpp, MoneyLog.h", "Server/game; changelook.cpp, char_item.cpp, char_skill.cpp, char.cpp, char.h, cmd_gm.cpp, cube_renewal.cpp, cube.cpp, db.cpp, db.h, exchange.cpp, exchange.h, input_db.cpp, input_main.cpp, item.cpp, item.h, log.cpp, log.h, packet.h, questlua_pc.cpp, shop_manager.cpp, shop.cpp, shop.h, shopEx.cpp, shopEx.h"
#define ENABLE_MDE_EFFECT									// 3D silah modellerine uygulanan parlama ve dinamik ýþýk (MDE - Motion Dynamic Effect) efektlerini etkinleþtirir; görsel derinlik katar;	"UserInterface; InstanceBase.cpp, InstanceBase.h, PythonPlayerSettingsModule.h"
#define ENABLE_PET_SYSTEM									// Karaktere eþlik eden, pasif bonuslar ve yiyecek/seviye mekanikleri içeren temel evcil hayvan sistemini etkinleþtirir;	"GameLib; ActorInstance.h, ItemData.h", "UserInterface; GameType.h, PythonApplicationModule.cpp, PythonItemModule.cpp, PythonNetworkStreamPhaseGameActor.cpp", "DumpProto; ItemCSVReader.cpp", "Server/common; item_length.h, length.h, VnumHelper.h", "Server/db; ProtoReader.cpp", "Server/game; affect.h, char_item.cpp, char.cpp, char.h, cmd_general.cpp, input_login.cpp, input_main.cpp, item_manager.cpp, item.cpp, item.h, ProtoReader.cpp, pvp.cpp, questlua_pet.cpp, questlua.cpp"
#define ENABLE_DISCORD_RPC									// Discord Rich Presence entegrasyonunu etkinleþtirir; oyuncunun Discord profilinde hangi karakteri oynadýðý, seviyesi ve haritasý gibi bilgileri gösterir;	"UserInterface; Discord.h, PythonApplication.cpp, PythonNetworkStream.cpp, PythonNetworkStream.h, PythonNetworkStreamPhaseGame.cpp"
#define ENABLE_AUTO_REFINE									// Oyun içi arayüzden tek týklamayla otomatik yükseltme (refine) yapýlabilmesini saðlar; tekrarlayan yükseltme iþlemlerini kolaylaþtýrýr;	"UserInterface; PythonApplicationModule.cpp"
#define ENABLE_DICE_SYSTEM									// Bir grup içinde canavar veya boss öldürüldüðünde düþen eþyanýn zar atýlarak grup üyeleri arasýnda adil biçimde daðýtýlmasýný saðlayan sistemi etkinleþtirir;	"UserInterface; Packet.h, PythonApplicationModule.cpp, PythonChat.cpp, PythonChatModule.cpp, PythonNetworkStreamPhaseGame.cpp", "Server/common; length.h", "Server/game; char_battle.cpp, char.cpp, cmd_general.cpp, desc.cpp, party.h, questlua_game.cpp, questlua_pc.cpp"
#define ENABLE_BLINK_ALERT									// Oyuncuya yeni bir özel mesaj (whisper) geldiðinde görev çubuðu simgesinin yanýp sönmesini saðlayarak görsel bildirim sunar;	"UserInterface; PythonApplication.cpp, PythonApplication.h, PythonApplicationModule.cpp"
#define ENABLE_STACK_LIMIT									// Envanterdeki ayný türden eþya yýðýnlarýnýn maksimum limitini varsayýlan 200'den 2000'e yükselterek büyük miktarda materyal taþýmayý mümkün kýlar;	"UserInterface; AbstractPlayer.h, GameType.h, Packet.h, PythonExchange.cpp, PythonExchange.h, PythonNetworkStream.h, PythonNetworkStreamModule.cpp, PythonNetworkStreamPhaseGame.cpp, PythonNetworkStreamPhaseGameItem.cpp, PythonPlayer.cpp, PythonPlayer.h, PythonPlayerModule.cpp", "Server/common; item_length.h, tables.h", "Server/game; char_item.cpp, char.cpp, char.h, cmd_general.cpp, input_main.cpp, item.cpp, OXEvent.cpp, OXEvent.h, packet.h, safebox.cpp, shop_manager.cpp, shop_manager.h, shop.cpp, shop.h, shopEx.cpp"
#define ENABLE_RENEWAL_CUBE									// Malzemeleri yeni eþyaya dönüþtürmek için kullanýlan küp sisteminin yenilenmiþ, daha dinamik ve geniþletilmiþ arayüz versiyonunu etkinleþtirir;	"UserInterface; Packet.h, PythonApplication.h, PythonApplicationModule.cpp, PythonCubeRenewal.cpp, PythonCubeRenewal.h, PythonNetworkStream.cpp, PythonNetworkStream.h, PythonNetworkStreamPhaseGame.cpp, StdAfx.h, UserInterface.cpp", "Server/game; char.h, cmd_general.cpp, cube_renewal.cpp, cube_renewal.h, cube.h, input_main.cpp, input.h, item_manager.cpp, packet_info.cpp, packet.h"
#define ENABLE_FIX_MOBS_LAG									// Çok sayýda canavar varlýðýnýn ayný anda render edilmesinden kaynaklanan FPS düþüþlerini ve takýlmalarý gidermek için grafik motoru düzeyinde optimizasyon uygular;	"EterLib; GrpBase.cpp, GrpBase.h, GrpDevice.cpp, GrpFontTexture.cpp, GrpFontTexture.h, GrpTextInstance.cpp", "UserInterface; PythonApplication.cpp"
#define ENABLE_MAP_TELEPORT									// GM/yönetici yetkisine sahip oyuncularýn minimap üzerine týklayarak anýnda o konuma ýþýnlanabilmesini saðlar;	"UserInterface; PythonApplicationModule.cpp, PythonMiniMap.cpp"
#define ENABLE_MOUNT_SYSTEM									// Binek hayvanlarý üzerine binip daha hýzlý hareket etmeyi, özel binek bonuslarýný ve binek çaðýrma mekaniklerini içeren resmi binek sistemini etkinleþtirir;	"GameLib; ActorInstance.h, ItemData.h", "UserInterface; GameType.h, PythonApplicationModule.cpp, PythonItemModule.cpp, PythonNetworkStreamPhaseGameActor.cpp", "DumpProto; ItemCSVReader.cpp", "Server/common; item_length.h, length.h, VnumHelper.h", "Server/db; ProtoReader.cpp", "Server/game; char_affect.cpp, char_battle.cpp, char_item.cpp, char_state.cpp, char.cpp, char.h, cmd_general.cpp, cmd_gm.cpp, input_login.cpp, input_main.cpp, item_manager.cpp, item.cpp, item.h, offlineshop_search_manager.cpp, ProtoReader.cpp, pvp.cpp, questlua_dungeon.cpp, questlua_global.cpp, questlua_horse.cpp, questlua_pc.cpp"
#define ENABLE_OBJ_SCALLING									// Oyun dünyasýndaki çevre nesnelerinin (aðaç, kaya, bina vb.) boyutunu sunucu/editor verisiyle dinamik olarak ölçeklendirmeyi saðlar;	"EterGrnLib; ThingInstance.cpp", "EterLib; GrpObjectInstance.cpp, GrpObjectInstance.h", "GameLib; ActorInstanceBattle.cpp"
#define ENABLE_FOXFS_ENCRYPT								// EterPack dosya sisteminin þifrelenmesini saðlayan Fox FS þifreleme katmanýný etkinleþtirir; binary içindeki paket anahtarlarýný gizleyerek tersine mühendisliði zorlaþtýrýr;	"EterPack; EterPackManager.cpp, EterPackManager.h", "GameLib; Property.cpp, Property.h, PropertyManager.cpp", "UserInterface; UserInterface.cpp"
#define ENABLE_SHOW_MOB_INFO								// Canavar isimlerinin üzerinde seviye ve saldýrganlýk (agresif/pasif) bilgisini gösteren metin etiketini etkinleþtirir;	"UserInterface; InstanceBase.cpp, InstanceBase.h, InstanceBaseEffect.cpp, NetworkActorManager.cpp, NetworkActorManager.h, Packet.h, PythonApplicationModule.cpp, PythonNetworkStreamPhaseGameActor.cpp, PythonSystem.cpp, PythonSystem.h, PythonSystemModule.cpp, PythonTextTail.cpp, PythonTextTail.h", "Server/game; building.cpp, char_manager.cpp, char_manager.h, char.cpp, char.h, cmd_gm.cpp, packet.h"
#define ENABLE_RENEWAL_QUEST								// Resmi sunuculardaki çok sayfalý, kategorize edilmiþ ve daha zengin içerikli görev (quest) arayüz sayfasýný etkinleþtirir;	"UserInterface; Packet.h, PythonApplicationModule.cpp, PythonNetworkStreamPhaseGame.cpp, PythonQuest.cpp, PythonQuest.h", "Server/game; packet.h, questmanager.cpp, questmanager.h, questpc.cpp"
#define ENABLE_CONFIG_MODULE								// Oyuncu ayarlarýnýn (grafik, ses, sistem tercihleri) bir yapýlandýrma dosyasýna kaydedilip oyunun her açýlýþýnda geri yüklenmesini saðlar;	"UserInterface; InstanceBase.cpp, PythonApplication.h, PythonBackgroundModule.cpp, PythonChat.cpp, PythonConfig.cpp, PythonConfig.h, PythonConfigModule.cpp, PythonItem.cpp, PythonNetworkStreamPhaseGameItem.cpp, StdAfx.h, UserInterface.cpp"
#define ENABLE_HAIR_SPECULAR								// Karakter saç modellerine speküler (parlama) ýþýk yansýmasý ekleyerek daha gerçekçi bir görünüm saðlar;	"GameLib; ActorInstance.h, ActorInstanceData.cpp", "UserInterface; InstanceBase.cpp"
#define ENABLE_MOB_DROP_INFO								// Bir canavarýn veya metin taþýnýn üzerine týklandýðýnda o varlýðýn hangi eþyalarý düþürebileceðini gösteren bilgi penceresini etkinleþtirir;	"UserInterface; Packet.h, PythonApplicationModule.cpp, PythonNetworkStream.cpp, PythonNetworkStream.h, PythonNetworkStreamModule.cpp, PythonNetworkStreamPhaseGame.cpp, PythonNonPlayerModule.cpp", "Server/game; char.cpp, char.h, input_main.cpp, input.h, item_manager.cpp, item_manager.h, packet_info.cpp, packet.h"
#define ENABLE_CHANGE_CHANNEL								// Oyuncunun mevcut haritada kalýrken sunucunun farklý bir kanalýna geçiþ yapabilmesini saðlayan kanal deðiþtirme özelliðini etkinleþtirir;	"UserInterface; PythonApplicationModule.cpp, PythonNetworkStreamPhaseGame.cpp", "Server/game; battle.cpp, char.cpp, char.h, cmd_general.cpp, cmd.cpp"
#define ENABLE_MOUNT_PET_SKIN								// Binek ve evcil hayvan görünümünü deðiþtiren kostüm (skin) sistemi; farklý binek/pet görüntüleri kullanmayý mümkün kýlar;	"GameLib; ItemData.h", "UserInterface; GameType.h, PythonApplicationModule.cpp, PythonItemModule.cpp", "DumpProto; ItemCSVReader.cpp", "Server/common; item_length.h, length.h", "Server/db; ProtoReader.cpp", "Server/game; char_item.cpp, char.cpp, char.h, cmd_general.cpp, item.cpp, item.h, offlineshop_search_manager.cpp, ProtoReader.cpp"
#define ENABLE_PENDANT_SYSTEM								// Resmi sürümdeki týlsým (pendant/belt) slot sistemini etkinleþtirir; karakterin ek týlsým takabilmesini ve bu týlsýmlarýn özel bonuslar saðlamasýný mümkün kýlar;	"GameLib; ItemData.h", "UserInterface; GameType.h, PythonApplicationModule.cpp, PythonItemModule.cpp, PythonSwitchbot.cpp, PythonWiki.cpp", "DumpProto; ItemCSVReader.cpp", "Server/common; item_length.h, length.h", "Server/db; ClientManagerBoot.cpp, ItemAwardManager.cpp, ProtoReader.cpp", "Server/game; char_item.cpp, char.h, item_attribute.cpp, item.cpp, item.h, ProtoReader.cpp, switchbot_manager.cpp"
#define ENABLE_ATTBONUS_METIN								// Metin taþlarýna karþý saldýrý bonusu özelliðini item attribute sistemiyle etkinleþtirir;	"UserInterface; PythonApplicationModule.cpp"
#define ENABLE_TEXTLINE_EMOJI								// Oyun içi yazý satýrlarýnda ve ipuçlarýnda (tooltip) emoji/ikon karakterlerin doðru biçimde gösterilmesini saðlar;	"EterLib; GrpTextInstance.cpp, GrpTextInstance.h, TextTag.cpp, TextTag.h", "UserInterface; PythonApplicationModule.cpp"
#define ENABLE_MESSENGER_TEAM								// Arkadaþ listesi penceresine grup/ekip üyeleri sekmesi ekleyerek takým arkadaþlarýný ayrý bir listede görmeyi saðlar;	"UserInterface; Packet.h, PythonApplicationModule.cpp, PythonMessenger.cpp, PythonMessenger.h, PythonNetworkStreamPhaseGame.cpp", "Server/game; messenger_manager.cpp, messenger_manager.h, packet.h"
#define ENABLE_DESTROY_DIALOG								// Bir eþyayý yere atarken önce bir onay diyaloðu açarak yanlýþlýkla eþya imha etmeyi önler; imha seçeneði de sunar;	"GameLib; ItemData.h", "UserInterface; Packet.h, PythonApplicationModule.cpp, PythonItemModule.cpp, PythonNetworkStream.h, PythonNetworkStreamModule.cpp, PythonNetworkStreamPhaseGameItem.cpp", "DumpProto; ItemCSVReader.cpp", "Server/db; ProtoReader.cpp", "Server/game; char_item.cpp, char.h, input_main.cpp, input.h, packet_info.cpp, packet.h, ProtoReader.cpp"
#define ENABLE_SORT_INVENTORY								// Envanter ve özel envanterdeki eþyalarý tek týklamayla türe veya sýraya göre otomatik düzenleyen sýralama sistemini etkinleþtirir;	"UserInterface; PythonApplicationModule.cpp", "Server/game; char.cpp, char.h, cmd_general.cpp, cmd.cpp"
#define ENABLE_GRAPHIC_ON_OFF								// Belirli grafik özelliklerini (efektler, gölgeler, zemin dokularý vb.) tek tek açýp kapatmayý mümkün kýlan geliþmiþ grafik yönetim sistemini etkinleþtirir;	"EffectLib; EffectManager.cpp, EffectManager.h", "GameLib; ActorInstance.h, ActorInstanceAttach.cpp", "UserInterface; InstanceBase.cpp, InstanceBaseEffect.cpp, PythonApplicationModule.cpp, PythonItem.cpp, PythonMiniMap.cpp, PythonNetworkStreamPhaseGameItem.cpp, PythonSystem.cpp, PythonSystem.h, PythonSystemModule.cpp, PythonTextTail.cpp"
#define ENABLE_PARTY_POSITION								// Ayný grupta olan oyuncularýn minimap üzerinde gerçek zamanlý konum iþaretlerinin gösterilmesini saðlar;	"UserInterface; Packet.h, PythonMiniMap.cpp, PythonMiniMap.h, PythonNetworkStream.cpp, PythonNetworkStream.h, PythonNetworkStreamPhaseGame.cpp, PythonPlayer.cpp", "Server/game; packet.h, party.cpp, party.h"
#define ENABLE_RENEWAL_SHOPEX								// Oyun içi dükkanýn birden fazla sayfa desteklemesini ve geniþletilmiþ ürün kapasitesine sahip olmasýný saðlayan yenilenmiþ ShopEx sistemini etkinleþtirir;	"UserInterface; GameType.h, Packet.h, PythonApplicationModule.cpp, PythonNetworkStreamPhaseGame.cpp, PythonShop.cpp", "Server/common; length.h, tables.h", "Server/db; ClientManager.cpp, ClientManager.h, ClientManagerBoot.cpp", "Server/game; input_db.cpp, packet.h, shop_manager.cpp, shop_manager.h, shop.cpp, shopEx.cpp"
#define ENABLE_INSTANT_PICKUP								// Oyuncunun eþyalarýn yanýna gitmeden, uzaktan ve anýnda zemine düþen eþyalarý toplayabilmesini saðlar;	"UserInterface; PythonApplicationModule.cpp, PythonItem.cpp, PythonItem.h, PythonPlayer.cpp, PythonPlayer.h, PythonPlayerInput.cpp, PythonPlayerModule.cpp"
#define ENABLE_VIEW_CHEST_DROP								// Bir sandýðýn üzerine týklandýðýnda içinde bulunabilecek olasý eþyalarýn listesini görüntülemeyi saðlar;	"UserInterface; Packet.h, PythonApplicationModule.cpp, PythonNetworkStream.cpp, PythonNetworkStream.h, PythonNetworkStreamModule.cpp, PythonNetworkStreamPhaseGame.cpp", "Server/game; input_main.cpp, input.h, item_manager.cpp, item_manager.h, packet_info.cpp, packet.h"
#define ENABLE_ATLAS_MARK_INFO								// Atlas (dünya haritasý) üzerindeki iþaretlere týklandýðýnda bölge adý, NPC bilgisi gibi detaylarý gösteren bilgi balonu sistemini etkinleþtirir;	"UserInterface; PythonMiniMap.cpp"
#define ENABLE_QUICK_SELL_ITEM								// Dükkanlarda eþyalarýn hýzlýca satýlabilmesi için tek týklamayla satýþ onayý veren kýsayol mekanizmasýný etkinleþtirir;	"UserInterface; Packet.h, PythonApplicationModule.cpp, PythonNetworkStream.h, PythonNetworkStreamModule.cpp, PythonNetworkStreamPhaseGameItem.cpp", "Server/game; char_item.cpp, char.h, input_main.cpp, input.h, packet_info.cpp, packet.h"
#define ENABLE_MESSENGER_BLOCK								// Belirli oyunculardan gelen mesajlarý ve etkileþimleri engelleyen oyuncu kara liste (block) sistemini etkinleþtirir;	"UserInterface; Packet.h, PythonApplicationModule.cpp, PythonMessenger.cpp, PythonMessenger.h, PythonNetworkStream.h, PythonNetworkStreamModule.cpp, PythonNetworkStreamPhaseGame.cpp", "Server/common; tables.h", "Server/game; BotPlayer.cpp, cmd_emotion.cpp, cmd_general.cpp, exchange.cpp, input_main.cpp, input_p2p.cpp, input.h, messenger_manager.cpp, messenger_manager.h, packet_info.cpp, packet.h, questlua_pc.cpp"
#define ENABLE_COINS_INVENTORY								// Standart Yang'a ek olarak alternatif bir para birimi (coin) sistemini envantere entegre eden yapýyý etkinleþtirir;	"UserInterface; Packet.h, PythonApplicationModule.cpp, PythonPlayerModule.cpp", "Server/game; char_item.cpp, char.cpp, char.h, cmd_gm.cpp, input_db.cpp"
#define ENABLE_EXTENDED_SAFEBOX								// Depodaki sayfa sayýsýný 3'ten 6'ya çýkararak çok daha fazla eþyanýn güvenli depolanmasýný saðlar;	"UserInterface; Packet.h, PythonApplicationModule.cpp, PythonNetworkStream.h, PythonNetworkStreamPhaseGameItem.cpp", "Server/common; length.h, tables.h", "Server/game; input_db.cpp, packet.h, safebox.cpp, safebox.h"
#define ENABLE_RENEWAL_SWITCHBOT							// Karakterin aura, binek veya ekipman gibi deðiþken nitelikleri için otomatik item deðiþimi yapan switchbot sisteminin yenilenmiþ versiyonunu etkinleþtirir;	"UserInterface; GameType.cpp, GameType.h, Packet.h, PythonApplication.cpp, PythonApplication.h, PythonApplicationModule.cpp, PythonNetworkStream.cpp, PythonNetworkStream.h, PythonNetworkStreamPhaseGame.cpp, PythonNetworkStreamPhaseGameItem.cpp, PythonPlayer.cpp, PythonPlayer.h, PythonPlayerModule.cpp, PythonSwitchbot.cpp, PythonSwitchbot.h, StdAfx.h, UserInterface.cpp", "Server/common; item_length.h, length.h, tables.h", "Server/db; ClientManagerPlayer.cpp", "Server/game; char_item.cpp, char.cpp, char.h, input_db.cpp, input_login.cpp, input_main.cpp, input_p2p.cpp, input.h, item_attribute.cpp, item_manager.h, item.cpp, item.h, main.cpp, packet_info.cpp, packet.h, switchbot_manager.cpp, switchbot_manager.h"
#define ENABLE_RENEWAL_BOOK_NAME							// Canavarlardan veya metin taþlarýndan düþen beceri kitaplarýnýn adýný ekrandaki öðe listesinde açýkça görünür hale getirir;	"UserInterface; Packet.h, PythonItem.cpp, PythonItem.h, PythonNetworkStreamPhaseGameItem.cpp", "Server/game; item.cpp, packet.h"
#define ENABLE_GUILD_RANK_SYSTEM							// Loncalarýn puan, üye sayýsý veya savaþ geçmiþine göre sýralandýðý lonca liderlik tablosunu (rank board) etkinleþtirir;	"UserInterface; AbstractPlayer.h, Packet.h, PythonApplication.h, PythonApplicationModule.cpp, PythonNetworkStream.cpp, PythonNetworkStream.h, PythonNetworkStreamPhaseGame.cpp, StdAfx.h, UserInterface.cpp", "Server/game; packet.h, questlua_pc.cpp"
#define ENABLE_LOAD_INDEX_BINARY							// Oyunun baþlangýcýnda kaynak dosya endeks (index) bilgilerini daha hýzlý yüklenen binary formattan okumasýný saðlar;	"UserInterface; PythonApplicationModule.cpp, UserInterface.cpp"
#define ENABLE_CLIENT_PERFORMANCE							// Harita yükleme, karakter modeli ve að akýþý optimizasyonlarý ile genel istemci performansýný artýrýr; yeni playersettingmodule sistemini devreye alýr;	"GameLib; MapOutdoor.cpp, MapOutdoor.h, MapOutdoorLoad.cpp, MapOutdoorUpdate.cpp, RaceData.h, RaceManager.cpp, RaceManager.h", "UserInterface; PythonApplication.cpp, PythonApplication.h, PythonApplicationModule.cpp, PythonItem.cpp, PythonItem.h, PythonNetworkStream.cpp, PythonNetworkStream.h, PythonNetworkStreamModule.cpp, PythonNetworkStreamPhaseGame.cpp, PythonNetworkStreamPhaseLoading.cpp, PythonNetworkStreamPhaseLogin.cpp, PythonNetworkStreamPhaseSelect.cpp, UserInterface.cpp"
#define ENABLE_ETERPACK_OBSCURING							// EterPack dosya paketine ait þifreleme anahtarlarýný binary içinde gizleyerek tersine mühendislik giriþimlerine karþý ek bir güvenlik katmaný saðlar;	"EterPack; EterPack.cpp"
#define ENABLE_RENEWAL_DEAD_PACKET							// Karakter öldüðünde belirli bir geri sayým sonrasýnda þehirde veya ayný yerde yeniden canlanma seçeneði sunan zamanlayýcýlý ölüm/canlanma sistemini etkinleþtirir;	"UserInterface; Packet.h, PythonApplicationModule.cpp, PythonNetworkStreamPhaseGame.cpp, PythonPlayerModule.cpp", "Server/game; char_battle.cpp, char.cpp, char.h, packet.h"
#define __BL__DETAILS_UI__									// Resmi oyuna benzer, karakterin tüm bonus ve istatistiklerini detaylý þekilde listeleyen yeni bonus bilgi panosunu etkinleþtirir;	"EterPythonLib; PythonWindow.cpp", "UserInterface; PythonApplicationModule.cpp, PythonItemModule.cpp"
#define ENABLE_KILL_STATISTICS								// Oyuncunun öldürdüðü canavar ve oyuncu sayýsýný, PvP/PvM istatistiklerini kaydeden ve gösteren sistemi etkinleþtirir;	"UserInterface; Packet.h, PythonApplicationModule.cpp, PythonNetworkStream.cpp, PythonNetworkStream.h, PythonNetworkStreamPhaseGame.cpp", "Server/common; tables.h", "Server/db; ClientManagerPlayer.cpp", "Server/game; char_battle.cpp, char.cpp, char.h, input_login.cpp, packet.h"
#define ENABLE_RENEWAL_SERVER_LIST							// Sunucu seçim ekranýnýn daha modern, kategorize ve görsel olarak iyileþtirilmiþ yenilenmiþ versiyonunu etkinleþtirir;	"UserInterface; PythonApplicationModule.cpp"
#define ENABLE_HIDE_COSTUME_SYSTEM							// Oyuncunun takýlý olan kostümünün görünümünü gizleyerek gerçek ekipmanýn görünmesini saðlayan kostüm gizleme seçeneðini etkinleþtirir;	"UserInterface; InstanceBase.cpp, InstanceBase.h, PythonApplicationModule.cpp, PythonPlayerModule.cpp", "Server/game; char.cpp, char.h, cmd_general.cpp, cmd.cpp, input_login.cpp"
#define ENABLE_ACCE_COSTUME_SYSTEM							// Aksesuar slotuna özel kostüm takýlmasýný, farklý görünümler elde edilmesini ve aksesuar kostümlerine özel efektlerin uygulanmasýný saðlayan sistemi etkinleþtirir;	"EterGrnLib; ThingInstance.cpp, ThingInstance.h", "EterLib; GrpObjectInstance.cpp, GrpObjectInstance.h", "EterPythonLib; PythonSlotWindow.h, PythonWindowManagerModule.cpp", "GameLib; ActorInstance.h, ActorInstanceAttach.cpp, ItemData.cpp, ItemData.h, ItemManager.cpp, ItemManager.h, RaceData.h", "UserInterface; GameType.cpp, GameType.h, InstanceBase.cpp, InstanceBase.h, NetworkActorManager.cpp, NetworkActorManager.h, Packet.h, PythonAcce.cpp, PythonAcce.h, PythonApplication.cpp, PythonApplication.h, PythonApplicationModule.cpp, PythonCharacterManagerModule.cpp, PythonCharacterModule.cpp, PythonItemModule.cpp, PythonNetworkStream.cpp, PythonNetworkStream.h, PythonNetworkStreamModule.cpp, PythonNetworkStreamPhaseGame.cpp, PythonNetworkStreamPhaseGameActor.cpp, PythonNetworkStreamPhaseGameItem.cpp, PythonNonPlayer.h, PythonPlayerModule.cpp, PythonPlayerSettingsModule.h, PythonRenderTargetModule.cpp, StdAfx.h, UserInterface.cpp", "DumpProto; ItemCSVReader.cpp", "Server/common; item_length.h, length.h, tables.h", "Server/db; ClientManagerLogin.cpp, ClientManagerPlayer.cpp, ProtoReader.cpp", "Server/game; BotPlayer.cpp, char_battle.cpp, char_item.cpp, char.cpp, char.h, cmd_general.cpp, constants.cpp, input_login.cpp, input_main.cpp, input.h, item.cpp, item.h, log.cpp, log.h, offlineshop_search_manager.cpp, packet_info.cpp, packet.h, ProtoReader.cpp, questlua_pc.cpp"
#define ENABLE_RENEWAL_MINIMAP_MARK							// Minimap üzerindeki NPC, canavar ve metin taþý iþaretlerini daha net ve kategorize edilmiþ yeni ikonlarla gösterir;	"UserInterface; PythonMiniMap.cpp"
#define ENABLE_TELEPORT_TO_A_FRIEND							// Arkadaþ listesindeki bir oyuncunun konumuna ýþýnlanma isteði gönderme ve kabul etme sistemini etkinleþtirir;	"UserInterface; Packet.h, PythonApplicationModule.cpp, PythonNetworkStream.h, PythonNetworkStreamModule.cpp, PythonNetworkStreamPhaseGame.cpp, PythonPlayerModule.cpp", "Server/game; char.cpp, char.h, input_main.cpp, packet.h, stdafx.h", "Server/library/liblua; stdafx.h"
#define ENABLE_METIN_STONES_MINIMAP							// Oyun haritasýndaki metin taþý konumlarýnýn minimap üzerinde görüntülenmesini saðlar;	"UserInterface; InstanceBase.h, InstanceBaseEffect.cpp, PythonApplicationModule.cpp, PythonCharacterManagerModule.cpp, PythonMiniMap.cpp, PythonMiniMap.h, PythonPlayerSettingsModule.h"
#define ENABLE_MULTI_LANGUAGE_SYSTEM						// Ýstemcinin birden fazla dili desteklemesini, sunucu tarafýndan gönderilen dil koduna göre otomatik dil geçiþi yapmasýný ve çok dilli metin görüntülemesini saðlar;	"UserInterface; AccountConnector.cpp, InstanceBase.cpp, InstanceBase.h, Locale.cpp, Locale.h, NetworkActorManager.cpp, NetworkActorManager.h, Packet.h, PythonApplication.cpp, PythonApplication.h, PythonApplicationModule.cpp, PythonChat.cpp, PythonMessenger.cpp, PythonMessenger.h, PythonMiniMap.cpp, PythonNetworkStream.cpp, PythonNetworkStream.h, PythonNetworkStreamModule.cpp, PythonNetworkStreamPhaseGame.cpp, PythonNetworkStreamPhaseGameActor.cpp, PythonTextTail.cpp, PythonTextTail.h", "DumpProto; dump_proto.cpp", "Server/common; length.h, tables.h, VnumHelper.h", "Server/db; ClientManager.cpp, ClientManager.h, ClientManagerLogin.cpp", "Server/game; BotPlayer.cpp, char_horse.cpp, char_item.cpp, char.cpp, char.h, cmd_general.cpp, config.cpp, constants.cpp, constants.h, db.cpp, desc_client.cpp, desc.cpp, desc.h, input_auth.cpp, input_db.cpp, input_main.cpp, input.h, item_manager.cpp, item.cpp, item.h, locale_service.cpp, locale_service.h, locale.cpp, messenger_manager.cpp, p2p.cpp, p2p.h, packet_info.cpp, packet.h, questlua_global.cpp, questlua_item.cpp, questlua_pc.cpp, questnpc.cpp"
#define ENABLE_WEAPON_COSTUME_SYSTEM						// Silah görünümünü deðiþtiren kostüm sistemini etkinleþtirir; silah kostümleri takýlarak gerçek silah istatistikleri korunurken farklý görsel efektler elde edilebilir;	"GameLib; ItemData.h", "UserInterface; GameType.h, InstanceBase.cpp, PythonApplicationModule.cpp, PythonItem.cpp, PythonItemModule.cpp, PythonNetworkStreamPhaseGameActor.cpp, PythonSwitchbot.cpp", "DumpProto; ItemCSVReader.cpp", "Server/common; item_length.h, length.h", "Server/db; ItemAwardManager.cpp, ProtoReader.cpp", "Server/game; char_item.cpp, char.cpp, char.h, cmd_general.cpp, cmd_gm.cpp, input_login.cpp, input_main.cpp, item_attribute.cpp, item.cpp, offlineshop_search_manager.cpp, ProtoReader.cpp"
#define ENABLE_VIEW_TARGET_PLAYER_HP						// Hedef çubuðunda seçilen oyuncunun veya canavarýn HP miktarýný sayýsal olarak görüntüler;	"UserInterface; InstanceBase.cpp, PythonApplicationModule.cpp, PythonNetworkStreamPhaseGame.cpp", "Server/game; char.cpp"
#define ENABLE_VIEW_TARGET_DECIMAL_HP						// HP deðerlerinin tam sayý yerine ondalýklý (virgüllü) formatta gösterilmesini saðlayarak daha hassas HP takibi yapar;	"UserInterface; Packet.h, PythonApplicationModule.cpp, PythonNetworkStreamPhaseGame.cpp", "Server/game; packet.h"
#define ENABLE_RENEWAL_CLIENT_VERSION						// Ýstemcinin sunucuya baðlanýrken sürüm numarasýný doðrulayan ve eski istemcilerin baðlantýsýný reddeden yeni sürüm kontrol mekanizmasýný etkinleþtirir;	"UserInterface; AccountConnector.cpp, Packet.h, PythonApplicationModule.cpp", "Server/game; input_auth.cpp, packet.h"
#define ENABLE_CANSEEHIDDENTHING_FOR_GM						// GM yetkisine sahip oyuncularýn görünmez moddaki karakterleri (hem normal görünmezlik hem de GM görünmezliði) tespit edebilmesini saðlar;	"UserInterface; InstanceBase.cpp, InstanceBaseEffect.cpp"
#define ENABLE_EXTENDED_WHISPER_DETAILS						// Özel mesaj (whisper) penceresinde alýcýnýn sunucu, kanal, ülke ve karakter bilgilerini gösteren geniþletilmiþ hedef bilgi panelini ve ülke bayraðý desteðini etkinleþtirir;	"UserInterface; Packet.h, PythonApplicationModule.cpp, PythonNetworkStream.cpp, PythonNetworkStream.h, PythonNetworkStreamModule.cpp, PythonNetworkStreamPhaseGame.cpp", "Server/game; input_main.cpp, input.h, packet_info.cpp, packet.h"
#define ENABLE_ENVIRONMENT_EFFECT_OPTION					// Yaðmur, kar, sis gibi atmosferik ortam efektlerini oyuncu tercihlerine göre açýp kapatmayý saðlayan ayarlar sistemi;	"GameLib; MapOutdoor.cpp, MapOutdoor.h", "UserInterface; PythonApplicationModule.cpp, PythonBackground.cpp, PythonBackground.h, PythonBackgroundModule.cpp, PythonSystem.cpp, PythonSystem.h, PythonSystemModule.cpp"
#define ENABLE_EXTEND_TIME_COSTUME_SYSTEM					// Süreli kostümlerin geçerlilik süresini uzatma (extend) mekanizmasýný etkinleþtirir;	"UserInterface; PythonApplicationModule.cpp", "Server/game; char_item.cpp"
#define ENABLE_FOV_OPTION									// Oyuncunun kamera görüþ açýsýný (Field of View) özelleþtirerek daha geniþ veya dar bir perspektif seçmesini saðlar;	"EterLib; GrpScreen.cpp, GrpScreen.h", "UserInterface; PythonApplication.cpp, PythonApplication.h, PythonApplicationModule.cpp, PythonMiniMap.cpp, PythonSystem.cpp, PythonSystem.h, PythonSystemModule.cpp"
#define ENABLE_RENDER_TARGET								// Karakter, evcil hayvan veya binek modellerini ayrý bir texture yüzeyine render ederek envanter/kostüm arayüzünde 3D önizleme sunmayý saðlar;	"EffectLib; EffectElementBaseInstance.cpp, EffectElementBaseInstance.h, EffectInstance.cpp, EffectInstance.h, EffectManager.cpp, EffectManager.h, ParticleSystemInstance.h", "EterGrnLib; ThingInstance.cpp, ThingInstance.h", "EterLib; Camera.cpp, Camera.h, GrpBase.cpp, GrpBase.h, GrpImageInstance.cpp, GrpImageInstance.h, GrpRenderTargetTexture.cpp, GrpRenderTargetTexture.h, RenderTarget.cpp, RenderTargetManager.cpp", "EterPythonLib; PythonWindow.cpp, PythonWindow.h, PythonWindowManager.cpp, PythonWindowManager.h, PythonWindowManagerModule.cpp", "GameLib; ActorInstance.h, ActorInstanceAttach.cpp", "UserInterface; InstanceBase.cpp, InstanceBase.h, PythonApplication.cpp, PythonApplication.h, PythonApplicationModule.cpp, PythonCharacterModule.cpp, PythonRenderTargetModule.cpp, StdAfx.h, UserInterface.cpp"
#define ENABLE_ATTBONUS_BOSS								// Boss canavarlarýna karþý ekstra saldýrý hasarý saðlayan bonus attribute tipini etkinleþtirir;	"UserInterface; PythonApplicationModule.cpp"
#define ENABLE_HUMAN_RESIST_PVP								// PvP savaþýnda yarý insan (human) ýrkýna karþý direnç bonusu attribute tipini etkinleþtirir;	"UserInterface; PythonApplicationModule.cpp"
#define ENABLE_EVENT_MANAGER								// Belirlenen zaman dilimlerinde otomatik olarak baþlatýlan ve sonlandýrýlan oyun içi etkinlikleri yönetmek için sunucu tarafý etkinlik yöneticisini etkinleþtirir;	"UserInterface; PythonGameEventManager.cpp, PythonGameEventManager.h, PythonGameEventManagerModule.cpp", "Server/game; event_manager.cpp, event_manager.h"
#define ENABLE_MULTI_TEXTLINE								// Tek bir metin kutusunda birden fazla satýr yazý gösterimini destekleyen çok satýrlý metin sistemi;	"EterLib; GrpTextInstance.cpp, GrpTextInstance.h", "EterPythonLib; PythonWindow.cpp, PythonWindow.h, PythonWindowManagerModule.cpp", "UserInterface; PythonApplicationModule.cpp"
#define ENABLE_RENEWAL_AFFECT								// Buff/debuff sistemi için yeni bir alt tip ve her aktif efekte ait görsel ikon desteði içeren yenilenmiþ affect altyapýsýný etkinleþtirir;	"GameLib; ItemData.h", "UserInterface; InstanceBase.h, PythonApplicationModule.cpp, PythonCharacterModule.cpp, PythonItemModule.cpp", "DumpProto; ItemCSVReader.cpp", "Server/common; item_length.h", "Server/db; ProtoReader.cpp", "Server/game; affect.h, char_item.cpp, char.h, item.cpp, item.h, ProtoReader.cpp"
#define ENABLE_OFFLINE_MESSAGE								// Çevrimdýþý bir oyuncuya mesaj býrakýlmasýný ve oyuncu tekrar çevrimiçi olduðunda bu mesajý almasýný saðlayan offline mesajlaþma sistemini etkinleþtirir;	"UserInterface; PythonChat.cpp, PythonChat.h, PythonNetworkStreamPhaseGame.cpp", "Server/common; length.h, tables.h", "Server/db; ClientManager.cpp, ClientManager.h", "Server/game; char.cpp, char.h, input_db.cpp, input_login.cpp, input_main.cpp, input.h"
#define ENABLE_RESTART_INSTANT								// Karakter öldüðünde belirli bir miktar Yang (örn. 500.000 Yang) ödeyerek öldüðü yerde anýnda canlanmayý saðlar;	"UserInterface; PythonApplicationModule.cpp", "Server/game; cmd_general.cpp, cmd.cpp"
#define ENABLE_RENEWAL_OX_EVENT								// Doðru/Yanlýþ sorularýna dayalý OX etkinliðinin resmi sunuculara yakýn þekilde yenilenmiþ ve geniþletilmiþ versiyonunu etkinleþtirir;	"UserInterface; Packet.h, PythonApplicationModule.cpp, PythonNetworkStreamPhaseGame.cpp, PythonChat.cpp, PythonChatModule.cpp, PythonNetworkStream.h, PythonNetworkStreamModule.cpp", "Server/common; length.h", "Server/game; char.cpp, cmd_gm.cpp, cmd.h, desc.cpp, input_main.cpp, input.h, OXEvent.cpp, packet_info.cpp, packet.h"
#define ENABLE_MULTI_FARM_BLOCK								// Ayný að üzerinden (ayný IP) ikiden fazla istemcinin eþ zamanlý çalýþtýrýlmasýný ve farm yapmasýný sunucu düzeyinde engelleyen sistemi etkinleþtirir;	"UserInterface; InstanceBase.h, PythonApplication.cpp, PythonApplication.h, PythonApplicationModule.cpp, PythonCharacterModule.cpp", "Server/common; tables.h", "Server/game; affect.h, char_affect.cpp, char_battle.cpp, char_item.cpp, char_manager.cpp, char_manager.h, char.cpp, char.h, cmd_general.cpp, cmd.cpp, input_login.cpp, input_p2p.cpp, input.h, packet_info.cpp, packet.h"
#define ENABLE_SPECIAL_INVENTORY							// Beceri kitaplarý, yükseltme taþlarý ve diðer özel materyaller için ana envanterden ayrý özel envanter sekmeleri sunan sistemi etkinleþtirir;	"UserInterface; GameType.cpp, GameType.h, PythonApplicationModule.cpp, PythonItemModule.cpp, PythonPlayer.cpp, PythonPlayer.h, PythonPlayerModule.cpp", "Server/common; length.h", "Server/db; ClientManager.cpp", "Server/game; char_hunting.cpp, char_item.cpp, char_quickslot.cpp, char.cpp, char.h, cmd_general.cpp, cmd_gm.cpp, cmd.cpp, cube_renewal.cpp, cube.cpp, exchange.cpp, input_db.cpp, input_main.cpp, item.cpp, item.h, offlineshop_manager.cpp, shop.cpp, shopEx.cpp"
#define ENABLE_STONE_SCALE_OPTION							// Haritada bulunan metin taþlarýnýn boyutunu oyuncu ayarlarýyla özelleþtirmeyi saðlar;	"UserInterface; InstanceBase.cpp, InstanceBase.h, InstanceBaseEffect.cpp, PythonApplicationModule.cpp, PythonSystem.cpp, PythonSystem.h, PythonSystemModule.cpp"
#define ENABLE_MAINTENANCE_SYSTEM							// Sunucu bakým sürecinde oyuncularý bilgilendiren, oyun içi bakým duyurusu ve geri sayým arayüzünü etkinleþtirir;	"UserInterface; PythonApplicationModule.cpp", "Server/game; cmd_general.cpp, cmd.cpp, input_login.cpp, input_p2p.cpp"
#define ENABLE_WIKI_SYSTEM									// Canavar özellikleri, item bilgileri ve drop listesi gibi oyun verilerini içeren oyun içi ansiklopedi (wiki) penceresini etkinleþtirir;	"EffectLib; EffectElementBaseInstance.cpp, EffectElementBaseInstance.h, EffectInstance.cpp, EffectInstance.h, EffectManager.cpp, EffectManager.h, EffectMeshInstance.cpp, ParticleSystemInstance.cpp", "EterPythonLib; PythonWindow.cpp, PythonWindow.h, PythonWindowManagerModule.cpp", "GameLib; ActorInstance.h, ActorInstanceAttach.cpp, ItemData.cpp, ItemData.h, ItemManager.h", "UserInterface; PythonApplication.cpp, PythonApplication.h, PythonApplicationModule.cpp, PythonItemModule.cpp, PythonNonPlayer.cpp, PythonNonPlayer.h, PythonNonPlayerModule.cpp, PythonWiki.cpp, PythonWiki.h, StdAfx.h, UserInterface.cpp"
#define ENABLE_PICKUP_ITEM_EFFECT							// Envantera veya özel envantera bir eþya alýndýðýnda görsel bir efekt animasyonu oynatýlmasýný saðlar;	"UserInterface; PythonApplicationModule.cpp", "Server/game; char_cards.cpp, char_item.cpp, char.h, cmd_gm.cpp, input_db.cpp, item.cpp, item.h"
#define ENABLE_RENEWAL_OFFLINESHOP							// Oyuncu dükkanýnýn yenilenmiþ versiyonunu etkinleþtirir; minimap üzerinde dükkan konumu gösterimi, arama desteði ve daha kapsamlý dükkan yönetimi içerir;	"GameLib; ActorInstance.cpp, ActorInstance.h", "UserInterface; InstanceBase.cpp, InstanceBase.h, InstanceBaseEffect.cpp, Packet.h, PythonApplicationModule.cpp, PythonCharacterManagerModule.cpp, PythonCharacterModule.cpp, PythonMiniMap.cpp, PythonMiniMap.h, PythonNetworkStream.cpp, PythonNetworkStream.h, PythonNetworkStreamCommand.cpp, PythonNetworkStreamModule.cpp, PythonNetworkStreamPhaseGame.cpp, PythonNetworkStreamPhaseGameItem.cpp, PythonPlayerSettingsModule.h, PythonShop.cpp, PythonShop.h, PythonTextTail.cpp", "Server/common; length.h, tables.h", "Server/db; ClientManager.cpp, ClientManager.h, ClientManagerBoot.cpp, ClientManagerOfflineshop.cpp, ClientManagerPlayer.cpp, ItemIDRangeManager.cpp", "Server/game; affect.h, char_affect.cpp, char_battle.cpp, char_item.cpp, char.cpp, char.h, cmd_general.cpp, cmd_gm.cpp, cmd.cpp, entity_view.cpp, input_db.cpp, input_login.cpp, input_main.cpp, input.h, main.cpp, offline_shop.cpp, offline_shop.h, offlineshop_manager.cpp, offlineshop_manager.h, offlineshop_search_manager.cpp, packet_info.cpp, packet.h, questlua_pc.cpp"
#define ENABLE_RENEWAL_TEAM_AFFECT							// Takým logolarýnýn ve grup etkilerinin yenilenmiþ görsel sunumuyla aktif edilmesini saðlar;	"UserInterface; InstanceBase.cpp, InstanceBase.h, InstanceBaseEffect.cpp, PythonApplicationModule.cpp, PythonPlayerSettingsModule.h", "Server/game; affect.h, char.cpp"
#define ENABLE_RENEWAL_TEXT_SHADOW							// Oyuncu ve NPC isimlerinin üstündeki metin etiketlerine gölge efekti eklenerek okunabilirliði artýran sistemi etkinleþtirir;	"UserInterface; PythonApplicationModule.cpp, PythonSystem.cpp, PythonSystem.h, PythonSystemModule.cpp, PythonTextTail.cpp"
#define ENABLE_SLOT_MARKING_SYSTEM							// Resmi sunuculardaki gibi envanter slotlarýnda özel renk/ikon iþaretlemesi yapýlabilmesini saðlar;	"EterPythonLib; PythonSlotWindow.cpp, PythonSlotWindow.h, PythonWindowManagerModule.cpp", "UserInterface; GameType.h, Packet.h, PythonApplicationModule.cpp, PythonNetworkStreamPhaseGame.cpp, PythonPlayerModule.cpp", "Server/game; exchange.cpp, packet.h"
#define ENABLE_RENEWAL_SKILL_SELECT							// Beceri öðrenme ve seçim arayüzünün daha kullanýcý dostu yeni pencere tasarýmýyla deðiþtirilmesini saðlar;	"UserInterface; PythonApplicationModule.cpp", "Server/game; char.cpp, char.h, cmd_general.cpp, cmd.cpp, input_login.cpp"
#define ENABLE_BONUS_COSTUME_SYSTEM							// Kostümlere ek attribute (bonus) ekleme ve bu bonuslarý deðiþtirme/yeniden yuvarlama sistemini etkinleþtirir;	"GameLib; ItemData.cpp, ItemData.h", "UserInterface; PythonApplicationModule.cpp, PythonPlayerModule.cpp", "DumpProto; ItemCSVReader.cpp", "Server/common; item_length.h, length.h", "Server/db; ClientManagerBoot.cpp, ItemAwardManager.cpp, ProtoReader.cpp", "Server/game; char_item.cpp, item_attribute.cpp, item.h, ProtoReader.cpp"
#define ENABLE_RENEWAL_SPECIAL_CHAT							// Yang transferi, eþya baðlantýsý ve özel komutlar için geliþtirilmiþ yenilenmiþ sohbet sistemi; týklanabilir item/yang linklerini destekler;	"UserInterface; Packet.h, PythonApplicationModule.cpp, PythonNetworkStream.cpp, PythonNetworkStream.h, PythonNetworkStreamPhaseGame.cpp", "Server/game; char_battle.cpp, char_item.cpp, char.cpp, char.h, packet.h"
#define ENABLE_LARGE_DYNAMIC_PACKET							// Standart paket boyutunu aþan büyük boyutlu dinamik veri paketlerinin gönderilmesine ve alýnmasýna olanak tanýr;	"EterLib; NetPacketHeaderMap.h", "UserInterface; Packet.h, PythonNetworkStream.cpp, PythonNetworkStreamModule.cpp", "Server/game; desc.cpp, packet.h"
#define ENABLE_CLIENT_LOCALE_STRING							// Ýstemcide kullanýlan metin dizelerinin (locale string) sunucudan baðýmsýz olarak istemci tarafýnda yönetilmesini ve dinamik dil deðiþimini saðlar;	"UserInterface; Packet.h, PythonApplication.cpp, PythonNetworkStream.cpp, PythonNetworkStream.h, PythonNetworkStreamPhaseGame.cpp, PythonNetworkStreamPhaseLoading.cpp", "Server/db; GuildManager.cpp", "Server/game; char.cpp, char.h, cmd_gm.cpp, cmd.h, desc.cpp, desc.h, input_p2p.cpp, input.h, packet_info.cpp, packet.h"
#define ENABLE_GUILD_LEADER_TEXTAIL							// Lonca liderlerinin karakter isminin üzerinde [Leader] etiketinin görünmesini saðlar;	"UserInterface; InstanceBase.cpp, InstanceBase.h, InstanceBaseEffect.cpp, NetworkActorManager.cpp, NetworkActorManager.h, Packet.h, PythonCharacterManager.cpp, PythonNetworkStreamPhaseGameActor.cpp, PythonTextTail.cpp, PythonTextTail.h, PythonTextTailModule.cpp", "Server/game; char.cpp, guild.cpp, guild.h, packet.h"
#define ENABLE_BOSS_EFFECT_OVER_HEAD						// Boss canavarlarýnýn baþýnýn üzerinde özel görsel efekt (krone/taç vb.) gösterilmesini saðlar;	"UserInterface; InstanceBase.cpp, InstanceBase.h, InstanceBaseEffect.cpp, PythonCharacterManagerModule.cpp, PythonNonPlayer.cpp, PythonNonPlayer.h, PythonPlayerSettingsModule.h"
#define ENABLE_MONSTER_TARGET_ELEMENT						// Her canavarýn hedeflendiðinde hangi elementel zayýflýða sahip olduðunu gösteren element bilgisi panelini etkinleþtirir;	"UserInterface; PythonApplicationModule.cpp, PythonNonPlayer.cpp, PythonNonPlayer.h, PythonNonPlayerModule.cpp"
#define ENABLE_AUTOMATIC_PICK_UP_SYSTEM						// Belirli filtrelere göre (eþya türü, ýrk) yerde düþen eþyalarýn oyuncu tarafýndan otomatik toplanmasýný saðlayan sistemi etkinleþtirir;	"UserInterface; GameType.h, InstanceBase.h, Packet.h, PythonApplicationModule.cpp, PythonCharacterModule.cpp, PythonNetworkStream.h, PythonNetworkStreamPhaseGameItem.cpp, PythonPlayer.cpp, PythonPlayer.h, PythonPlayerInput.cpp, PythonPlayerModule.cpp", "Server/common; tables.h", "Server/db; ClientManagerPlayer.cpp", "Server/game; affect.h, char_affect.cpp, char_battle.cpp, char_item.cpp, char.cpp, char.h, cmd_general.cpp, cmd.cpp, input_login.cpp, input_main.cpp, input.h, item.cpp, packet_info.cpp, packet.h"
#define ENABLE_OFFLINESHOP_SEARCH_SYSTEM					// Yenilenmiþ oyuncu dükkan sistemine entegre, ürün adý veya türüne göre tüm aktif dükkanlarý arayabilen geliþmiþ arama motorunu etkinleþtirir;	"GameLib; MapOutdoor.cpp, MapOutdoor.h", "UserInterface; Packet.h, PythonApplication.h, PythonApplicationModule.cpp, PythonBackground.cpp, PythonBackground.h, PythonBackgroundModule.cpp, PythonItemModule.cpp, PythonNetworkStream.cpp, PythonNetworkStream.h, PythonNetworkStreamModule.cpp, PythonNetworkStreamPhaseGame.cpp, PythonPrivateShopSearch.cpp, PythonPrivateShopSearch.h, StdAfx.h, UserInterface.cpp", "Server/game; char.cpp, char.h, input_main.cpp, input.h, offlineshop_manager.cpp, offlineshop_manager.h, offlineshop_search_manager.cpp, packet_info.cpp, packet.h, utils.cpp, utils.h"
#define ENABLE_PYTHON_DYNAMIC_MODULE_NAME					// Python modül isimlerinin derleme zamanýnda dinamik olarak atanmasýný saðlayan ek güvenlik katmanýný etkinleþtirir; tersine mühendisliði zorlaþtýrýr;	"UserInterface; PythonApplicationModule.cpp, PythonCharacterManagerModule.cpp, PythonCharacterModule.cpp, PythonDynamicModuleNames.cpp, PythonDynamicModuleNames.h, PythonNetworkStreamModule.cpp, PythonPackModule.cpp, PythonPlayerModule.cpp, StdAfx.h, UserInterface.cpp"
#define ENABLE_SKILL_COLOR_SYSTEM							// Beceri efekt renklerini özelleþtirmeyi saðlayan sistemi etkinleþtirir; farklý beceri seviyeleri veya oyuncu tercihleri için renk atamasý yapýlabilir;	"EffectLib; EffectInstance.cpp, EffectInstance.h, EffectManager.cpp, EffectManager.h, ParticleSystemData.cpp, ParticleSystemData.h", "EterBase; CRC32.cpp, CRC32.h", "EterPythonLib; PythonWindowManagerModule.cpp", "GameLib; ActorInstance.cpp, ActorInstance.h, ActorInstanceAttach.cpp, ActorInstanceData.cpp, ActorInstanceMotionEvent.cpp, FlyingInstance.cpp, FlyingInstance.h, FlyingObjectManager.cpp, FlyingObjectManager.h", "UserInterface; GameType.h, InstanceBase.cpp, InstanceBase.h, InstanceBaseEffect.cpp, Locale_inc.h, NetworkActorManager.cpp, NetworkActorManager.h, Packet.h, PythonApplicationModule.cpp, PythonConfig.cpp, PythonConfig.h, PythonConfigModule.cpp, PythonNetworkStream.h, PythonNetworkStreamPhaseGame.cpp, PythonNetworkStreamPhaseGameActor.cpp, PythonPlayerModule.cpp", "Server/common; length.h, tables.h", "Server/db; Cache.cpp, Cache.h, ClientManager.cpp, ClientManager.h, ClientManagerPlayer.cpp, Main.cpp, QID.h", "Server/game; char_skill.cpp, char.cpp, char.h, input_db.cpp, input_main.cpp, input.h, packet_info.cpp, packet.h"
#ifdef ENABLE_SKILL_COLOR_SYSTEM
#define ENABLE_5LAYER_SKILL_COLOR					// Beceri renk sistemi için 5 katmanlý renk atamasýna olanak tanýyarak daha zengin ve karmaþýk renk kombinasyonlarýna izin verir;	"UserInterface; PythonApplicationModule.cpp"
#endif
#define ENABLE_CLIP_MASKING                     			// Resmi sürümdeki gibi UI öðelerini görünür alan dýþýnda kýrpan clip masking (görsel kýrpma) özelliðini etkinleþtirir;	"EterLib; GrpExpandedImageInstance.cpp, GrpExpandedImageInstance.h, GrpImageInstance.cpp, GrpImageInstance.h, GrpTextInstance.cpp", "EterPythonLib; PythonWindow.cpp, PythonWindow.h, PythonWindowManagerModule.cpp", "UserInterface; PythonApplicationModule.cpp, PythonChat.cpp"
#define ENABLE_UTF8_ENCODING                    			// Ýstemcinin metin kodlamasýný Windows-1254 (Türkçe) yerine UTF-8 olarak kullanmasýný saðlayarak çok dilli karakter setlerini doðru görüntüler;	"EterLib; TextBar.cpp, Util.cpp", "UserInterface; Locale.cpp"
#define ENABLE_NPC_WEAR_ITEM                    			// NPC modellerinin üzerinde özel ekipman ve kýyafet görüntülenebilmesini saðlar; görsel çeþitlilik için kullanýlýr;	"GameLib; ActorInstanceData.cpp", "UserInterface; InstanceBase.cpp, PythonApplication.cpp, PythonNonPlayer.cpp, PythonNonPlayer.h"
#define ENABLE_HUNTING_SYSTEM                   			// Belirli canavarlarý öldürme veya eþya toplama gibi hedef bazlý özgün görevler içeren avcýlýk (hunting) sistemini etkinleþtirir;	"UserInterface; Packet.h, PythonApplicationModule.cpp, PythonNetworkStream.cpp, PythonNetworkStream.h, PythonNetworkStreamModule.cpp, PythonNetworkStreamPhaseGame.cpp", "Server/common; service.h", "Server/game; char_battle.cpp, char_hunting.cpp, char.cpp, char.h, constants.cpp, constants.h, input_login.cpp, input_main.cpp, input.h, packet_info.cpp, packet.h"
#define ENABLE_EMOTICONS_SYSTEM                 			// Sohbet kanalýnda ve özel mesajlarda (whisper) emoji/ikon kullanýmýný destekleyen emoji sistemini etkinleþtirir;	"EterLib; GrpTextInstance.cpp, GrpTextInstance.h, TextBar.cpp, TextBar.h, TextTag.cpp, TextTag.h", "EterPythonLib; PythonWindow.cpp, PythonWindow.h, PythonWindowManagerModule.cpp", "UserInterface; PythonApplicationModule.cpp, PythonChat.cpp, PythonChat.h, PythonChatModule.cpp, PythonNetworkStreamPhaseGame.cpp, PythonTextTail.cpp, PythonTextTail.h", "Server/common; length.h", "Server/db; ClientManager.cpp", "Server/game; cmd.cpp, input_main.cpp"
#define ENABLE_GROWTH_PET_SYSTEM                			// Resmi Metin2 sürümündeki gibi peti besleyerek büyütebileceðiniz, seviye kazandýrabileceðiniz ve özel beceriler öðretebileceðiniz kapsamlý büyüme (growth) pet sistemini etkinleþtirir;	"EterLib; GrpExpandedImageInstance.cpp", "GameLib; ActorInstance.cpp, ActorInstance.h, ItemData.h", "UserInterface; GameType.h, InstanceBase.cpp, InstanceBase.h, InstanceBaseBattle.cpp, InstanceBaseEffect.cpp, Locale_inc.h, NetworkActorManager.cpp, NetworkActorManager.h, Packet.h, PythonApplication.cpp, PythonApplicationModule.cpp, PythonCharacterManager.cpp, PythonCharacterManagerModule.cpp, PythonCharacterModule.cpp, PythonChatModule.cpp, PythonItemModule.cpp, PythonNetworkStream.cpp, PythonNetworkStream.h, PythonNetworkStreamModule.cpp, PythonNetworkStreamPhaseGame.cpp, PythonNetworkStreamPhaseGameActor.cpp, PythonNetworkStreamPhaseGameItem.cpp, PythonNetworkStreamPhaseLoading.cpp, PythonPlayer.cpp, PythonPlayer.h, PythonPlayerModule.cpp, PythonPlayerSettingsModule.h, PythonSkill.cpp, PythonSkill.h", "DumpProto; ItemCSVReader.cpp", "Server/common; item_length.h, length.h, tables.h, VnumHelper.h", "Server/db; Cache.cpp, Cache.h, ClientManager.cpp, ClientManager.h, ClientManagerBoot.cpp, ClientManagerPlayer.cpp, ProtoReader.cpp, QID.h", "Server/game; affect.h, battle.cpp, char_battle.cpp, char_item.cpp, char_manager.cpp, char_state.cpp, char.cpp, char.h, cmd_gm.cpp, cmd.cpp, constants.cpp, constants.h, cube_renewal.cpp, cube.cpp, dungeon.cpp, exchange.cpp, guild.cpp, input_db.cpp, input_main.cpp, input.h, item.cpp, main.cpp, offlineshop_search_manager.cpp, packet_info.cpp, packet.h, ProtoReader.cpp, pvp.cpp, questlua_dungeon.cpp, safebox.cpp, safebox.h, sectree_manager.cpp, shop_manager.cpp, SnakeLair.cpp, typedef.h, WhiteDragon.cpp"
#ifdef ENABLE_GROWTH_PET_SYSTEM
#define ENABLE_UPBRINGING_PET_CONQUEROR_LEVEL       // Resmi sürümdeki büyüme pet þampiyon (conqueror) seviye sistemini etkinleþtirir; pet belirli bir seviyeye ulaþtýðýnda þampiyon moduna geçiþ yapabilir;	"UserInterface; PythonApplicationModule.cpp"
#endif
#define ENABLE_CHANGE_LOOK_SYSTEM               			// Bir eþyanýn görünümünü baþka bir eþyanýn görünümüyle deðiþtirirken istatistiklerini koruyan görünüm deðiþtirme (transmog) sistemini etkinleþtirir;	"EterPythonLib; PythonSlotWindow.cpp, PythonSlotWindow.h, PythonWindowManagerModule.cpp", "GameLib; ItemData.cpp, ItemData.h", "UserInterface; AbstractPlayer.h, GameType.cpp, GameType.h, Packet.h, PythonApplicationModule.cpp, PythonChatModule.cpp, PythonExchange.cpp, PythonExchange.h, PythonExchangeModule.cpp, PythonItem.cpp, PythonItem.h, PythonItemModule.cpp, PythonNetworkStream.cpp, PythonNetworkStream.h, PythonNetworkStreamModule.cpp, PythonNetworkStreamPhaseGame.cpp, PythonNetworkStreamPhaseGameItem.cpp, PythonPlayer.cpp, PythonPlayer.h, PythonPlayerModule.cpp, PythonPrivateShopSearch.cpp, PythonSafeBox.cpp, PythonShop.cpp", "Server/common; tables.h", "Server/db; Cache.cpp, ClientManager.cpp, ClientManagerOfflineshop.cpp, ClientManagerPlayer.cpp", "Server/game; changelook.cpp, changelook.h, char_item.cpp, char.cpp, char.h, cmd_general.cpp, cube_renewal.cpp, cube.cpp, exchange.cpp, input_db.cpp, input_main.cpp, input.h, item_manager.cpp, item.cpp, item.h, offline_shop.cpp, offlineshop_manager.cpp, offlineshop_search_manager.cpp, packet_info.cpp, packet.h, questlua_game.cpp, questlua_item.cpp, safebox.cpp, shop_manager.cpp, shop.cpp, unique_item.h"
#define ENABLE_AURA_COSTUME_SYSTEM              			// Karaktere özel parlayan ve animasyonlu bir aura (halo) görsel efekti ekleyen kostüm sistemini etkinleþtirir;	"EffectLib; EffectElementBaseInstance.cpp, EffectElementBaseInstance.h, EffectInstance.cpp, EffectInstance.h, EffectManager.cpp, EffectManager.h, EffectMeshInstance.cpp, ParticleSystemInstance.cpp", "EterPythonLib; PythonSlotWindow.h, PythonWindowManagerModule.cpp", "GameLib; ActorInstance.h, ActorInstanceAttach.cpp, ActorInstanceMotionEvent.cpp, ItemData.cpp, ItemData.h, ItemManager.cpp, ItemManager.h, RaceData.h", "UserInterface; GameType.cpp, GameType.h, InstanceBase.cpp, InstanceBase.h, InstanceBaseEffect.cpp, NetworkActorManager.cpp, NetworkActorManager.h, Packet.h, PythonApplication.cpp, PythonApplicationModule.cpp, PythonCharacterModule.cpp, PythonItemModule.cpp, PythonNetworkStream.cpp, PythonNetworkStream.h, PythonNetworkStreamModule.cpp, PythonNetworkStreamPhaseGame.cpp, PythonNetworkStreamPhaseGameActor.cpp, PythonNonPlayer.h, PythonPlayer.cpp, PythonPlayer.h, PythonPlayerModule.cpp, PythonRenderTargetModule.cpp", "DumpProto; ItemCSVReader.cpp", "Server/common; item_length.h, length.h, tables.h", "Server/db; ClientManagerLogin.cpp, ClientManagerPlayer.cpp, ProtoReader.cpp", "Server/game; BotPlayer.cpp, char_aura.cpp, char_battle.cpp, char_item.cpp, char.cpp, char.h, cmd_general.cpp, constants.cpp, constants.h, cube_renewal.cpp, cube.cpp, exchange.cpp, input_db.cpp, input_login.cpp, input_main.cpp, input.h, item_attribute.cpp, item_manager.cpp, item.cpp, item.h, offlineshop_search_manager.cpp, packet_info.cpp, packet.h, ProtoReader.cpp, questlua_game.cpp, questlua_pc.cpp, shop_manager.cpp, unique_item.h"
#define ENABLE_PYTHON_EVENT_FUNCTIONS           			// Oyun içi animasyonlar, ses ve diðer olaylar için resmi sürümdeki gibi Python tabanlý event fonksiyonu altyapýsýný etkinleþtirir;	"EterLib; GrpTextInstance.cpp, GrpTextInstance.h, parser.cpp, parser.h", "UserInterface; PythonEventManager.cpp, PythonEventManager.h, PythonEventManagerMoudle.cpp"
#define ENABLE_RENEWAL_TELEPORT_SYSTEM          			// Harita içi ýþýnlanma noktalarý ve karakter arasý geçiþler için daha geliþmiþ yenilenmiþ ýþýnlanma altyapýsýný etkinleþtirir;	"UserInterface; PythonApplicationModule.cpp, PythonNetworkStreamCommand.cpp", "Server/game; char.cpp, char.h, cmd_general.cpp, cmd.cpp"
#define ENABLE_INVENTORY_EXPANSION_SYSTEM       			// Oyuncunun envanter alanýný geniþleten ekstra sekme veya slotlar satýn almasýna olanak tanýyan resmi envanter geniþletme sistemini etkinleþtirir;	"UserInterface; PythonApplicationModule.cpp", "Server/common; length.h, tables.h", "Server/db; ClientManagerPlayer.cpp", "Server/game; char_item.cpp, char.cpp, char.h, cmd_general.cpp, cmd.cpp, exchange.cpp, input_login.cpp"
//#define ENABLE_MORE_FPS									// FPS sýnýr yükseltme; daha yüksek kare hýzlarýna izin verir (kapalý);	"EterBase; Timer.cpp, Timer.h", "EterGrnLib; ModelInstance.h", "UserInterface; PythonApplication.cpp"
#define ENABLE_GM_INV_EFFECT         						// GM /inv komutuyla kullanýlan görünmezlik efektinin resmi güncel görünümünü etkinleþtirir;	"UserInterface; PythonNetworkStreamPhaseGameItem.cpp", "Server/game; cmd_gm.cpp"
#define ENABLE_MINIMAP_SMOOTH_ZOOM             				// Minimap yakýnlaþtýrma ve uzaklaþtýrma iþlemini kademeli animasyonla gerçekleþtiren yumuþak zoom sistemini etkinleþtirir;	"UserInterface; PythonMiniMap.cpp, PythonMiniMap.h"
#define ENABLE_OFFICAL_FEATURES								// Resmi Metin2 sürümünden tersine mühendislikle elde edilmiþ çeþitli UI/grafik iyileþtirmelerini etkinleþtirir;	"EterLib; GrpImageInstance.cpp, GrpImageInstance.h", "EterPythonLib; PythonWindow.cpp, PythonWindow.h, PythonWindowManagerModule.cpp"
#define WJ_SHOW_NPC_QUEST_NAME              				// NPC'lerin üzerindeki metin etiketinde aktif görev adýný göstererek hangi NPC'nin göreve katkýsý olduðunu kolayca anlamayý saðlar;	"UserInterface; PythonApplicationModule.cpp"
#define ENABLE_ATLAS_SCALE									// Dünya atlasýnýn (harita) ölçeðini ve görüntüleme boyutunu ayarlama sistemini etkinleþtirir;	"UserInterface; PythonApplicationModule.cpp, PythonMiniMap.cpp, PythonMiniMap.h, PythonMiniMapModule.cpp"
#define ENABLE_FALLING_EFFECT_SYSTEM						// Zeminde düþen eþyalarýn üzerine özel görsel efekt eklenerek dikkat çekiciliðini artýran sistemi etkinleþtirir;	"UserInterface; PythonItem.cpp, PythonItem.h"
#define ENABLE_STANDING_MOUNT								// Karakterin üzerinde durduðu ama normal binek gibi hareket etmeyen özel binek türlerini (sörf tahtasý, kaykay vb.) destekleyen sistemi etkinleþtirir;	"GameLib; ActorInstance.cpp, ActorInstanceAttach.cpp, ActorInstanceCollisionDetection.cpp, RaceData.cpp, RaceManager.cpp, RaceMotionData.h", "UserInterface; InstanceBase.cpp, InstanceBase.h, InstanceBaseBattle.cpp, Locale_inc.h, PythonApplicationModule.cpp, PythonNetworkStreamCommand.cpp, PythonPlayerSettingsModule.cpp, PythonPlayerSettingsModule.h, PythonPlayerSkill.cpp", "Server/common; service.h", "Server/game; BotPlayer.cpp, char_skill.cpp, pvp.cpp"
#ifdef ENABLE_STANDING_MOUNT
#define STANDING_MOUNT_VNUM_1 40003 				// Turbo Sörf Tahtasý
#define STANDING_MOUNT_VNUM_2 40004 				// Wukong'un Fýrtýnasý
#define STANDING_MOUNT_VNUM_3 40005 				// Wukong'un Gürlemesi
#define SURFBOARD STANDING_MOUNT_VNUM_1 			// Eski sistemlerle uyumluluk için alias
#endif
#define ENABLE_RIDING_EXTENDED 								// Resmi sürümdeki at besleme, seviye yükseltme ve at yetenekleri sistemini içeren geniþletilmiþ at/binek seviye sistemini etkinleþtirir;	"UserInterface; GameType.h, InstanceBase.cpp, Packet.h, PythonApplication.h, PythonApplicationModule.cpp, PythonMountUpGrade.cpp, PythonMountUpGrade.h, PythonNetworkStream.cpp, PythonNetworkStream.h, PythonNetworkStreamPhaseGame.cpp, PythonPlayerModule.cpp, StdAfx.h, UserInterface.cpp", "Server/common; length.h, tables.h", "Server/db; ClientManagerPlayer.cpp", "Server/game; char_horse.cpp, char_item.cpp, char_skill.cpp, char.cpp, char.h, horse_rider.cpp, horse_rider.h, input_main.cpp, input.h, mount_up_grade.cpp, mount_up_grade.h, packet_info.cpp, packet.h, questlua_game.cpp, unique_item.h"
#define ENABLE_SPIRIT_STONE_READING							// Ruh taþlarýnýn (spirit stone) okunmasýný ve karaktere attribute kazandýrmasýný saðlayan sistemi etkinleþtirir;	"UserInterface; PythonApplicationModule.cpp", "Server/game; char_item.cpp, char.cpp, char.h, cmd_general.cpp, cmd.cpp"
#define ENABLE_SKILL_BOOK_READING							// Beceri kitaplarýnýn okunmasýný ve pasif beceri seviyesinin yükseltilmesini saðlayan sistemi etkinleþtirir;	"UserInterface; PythonApplicationModule.cpp", "Server/game; char_item.cpp, char.cpp, char.h, cmd_general.cpp, cmd.cpp"
#define __AUTO_HUNT__										// Belirli filtrelere göre otomatik saldýrý, eþya toplama ve hareket yapan tam kapsamlý otomatik av sistemini etkinleþtirir;	"UserInterface; AbstractPlayer.h, InstanceBase.h, InstanceBaseBattle.cpp, PythonApplicationModule.cpp, PythonCharacterManager.cpp, PythonCharacterManager.h, PythonCharacterModule.cpp, PythonMiniMap.cpp, PythonMiniMap.h, PythonMiniMapModule.cpp, PythonNetworkStreamCommand.cpp, PythonPlayer.cpp, PythonPlayer.h, PythonPlayerInput.cpp, PythonPlayerSettingsModule.h, StdAfx.cpp, StdAfx.h", "Server/game; affect.h, char_battle.cpp, char_item.cpp, char_manager.cpp, char_manager.h, char.cpp, char.h, cmd_general.cpp, cmd.cpp"
#define ENABLE_AUTO_SELL_SYSTEM								// Seçilen eþya türlerini otomatik olarak en yakýn tüccara satan sistemi etkinleþtirir;	"UserInterface; Packet.h, PythonApplicationModule.cpp", "Server/common; service.h, tables.h", "Server/game; char_item.cpp, char.cpp, char.h, cmd_general.cpp, cmd.cpp, input_main.cpp, input.h, item.cpp, item.h, packet.h"
#define ENABLE_STYLE_ATTRIBUTE_SYSTEM      					// Eþyalara eklenebilecek seçmeli özel (kadim/eski tip) efsun sistemi; belirli özellikler arasýndan seçim yapýlmasýna olanak tanýr;	"UserInterface; Packet.h, PythonApplicationModule.cpp, PythonNetworkStream.h, PythonNetworkStreamModule.cpp, PythonNetworkStreamPhaseGameItem.cpp", "Server/game; char_item.cpp, char.h, input_main.cpp, input.h, item_attribute.cpp, item.h, packet_info.cpp, packet.h"
#define ENABLE_GM_MOB_VNUM_DISPLAY   						// GM yetkisindeki oyunculara canavar VNUM (sanal numara) bilgisini oyun içi veya log çýktýsýnda gösterir; test ve yönetim için kullanýlýr;	"UserInterface; PythonTextTail.cpp"
#define ENABLE_RENDERING_ONLY_IN_AREA						// Harita bölgesi dýþýnda kalan aðýr efektlerin render edilmesini engelleyerek performansý artýran alan bazlý render filtresi;	"EffectLib; EffectInstance.h", "EterBase; Utils.h", "GameLib; Area.cpp, Area.h, MapOutdoor.h, MapOutdoorUpdate.cpp"
#define ENABLE_RENDERING_ONLY_IN_AREA_V2					// Render alaný filtresi sisteminin ikinci versiyonu; harita yükleme sürecini optimize ederek daha verimli hale getirir;	"EterBase; Utils.h", "GameLib; Area.cpp, Area.h, MapOutdoor.h, MapOutdoorUpdate.cpp"
#define ENABLE_NEW_SHINING_EFFEKT							// Yüksek seviyeli silah ve zýrhlara uygulanan yeni nesil resmi parlama (glow/shining) efekt sistemini etkinleþtirir;	"UserInterface; Locale_inc.h, PythonApplicationModule.cpp"
#ifdef ENABLE_NEW_SHINING_EFFEKT
#define ENABLE_LVL115_ARMOR_EFFECT					// 115. seviye zýrhlara özel parlama efektini aktif eder;	"UserInterface; InstanceBase.cpp, PythonApplicationModule.cpp"
#define ENABLE_LVL96_WEAPON_EFFECT					// 96. seviye silahlara özel parlama efektini aktif eder;	"UserInterface; InstanceBase.cpp, InstanceBase.h, PythonApplicationModule.cpp, PythonPlayerSettingsModule.h"
#define ENABLE_LVL96_ARMOR_EFFECT					// 96. seviye zýrhlara özel parlama efektini aktif eder;	"UserInterface; InstanceBase.cpp, InstanceBase.h, PythonApplicationModule.cpp, PythonPlayerSettingsModule.h"

//#define USE_WEAPON_COSTUME_WITH_EFFECT			// Silah kostümlerinin de geliþtirme/parlama efektini göstermesini saðlar;	"UserInterface; PythonApplicationModule.cpp"
//#define USE_BODY_COSTUME_WITH_EFFECT				// Zýrh kostümlerinin de geliþtirme/parlama efektini göstermesini saðlar;	"UserInterface; InstanceBase.h, PythonApplicationModule.cpp, PythonPlayerSettingsModule.h"
#endif
#define ENABLE_PITTY_REFINE                    				// Birden fazla yükseltme baþarýsýzlýðý sonrasýnda baþarý þansýný kademeli olarak artýran pity (garanti yükseltme) sistemini etkinleþtirir;	"GameLib; ItemData.h", "UserInterface; Packet.h, PythonApplicationModule.cpp, PythonNetworkStream.h, PythonNetworkStreamModule.cpp, PythonNetworkStreamPhaseGame.cpp", "DumpProto; ItemCSVReader.cpp", "Server/common; item_length.h", "Server/db; ProtoReader.cpp", "Server/game; char_item.cpp, char.cpp, char.h, input_login.cpp, input_main.cpp, item.cpp, item.h, packet.h, ProtoReader.cpp"
#define ENABLE_HYPERLINK_ITEM_ICON                  		// Görev (quest) metinlerinde ve diyaloglarda item adýnýn yanýnda küçük eþya simgesi gösterilmesini etkinleþtirir;	"UserInterface; PythonApplicationModule.cpp"
#define ENABLE_DIRECTX9_UPDATE                				// DirectX 9 grafiklerini daha modern D3DX9 kütüphane güncellemeleriyle destekleyen uyumluluk katmanýný etkinleþtirir; shader ve texture iþleme iyileþtirir;	"EffectLib; EffectInstance.cpp, EffectManager.cpp, EffectMesh.h, EffectMeshInstance.cpp, SimpleLightData.cpp, SimpleLightData.h, SimpleLightInstance.cpp", "EterBase; DDSTextureLoader.cpp, DDSTextureLoader.h", "EterGrnLib; Material.cpp, Material.h, Model.cpp, Model.h, ModelInstance.h, ModelInstanceModel.cpp, ModelInstanceRender.cpp", "EterLib; BlockTexture.cpp, BlockTexture.h, Camera.cpp, Decal.cpp, DibBar.cpp, GrpBase.cpp, GrpBase.h, GrpDetector.cpp, GrpDetector.h, GrpDevice.cpp, GrpDevice.h, GrpExpandedImageInstance.cpp, GrpImageInstance.cpp, GrpImageTexture.cpp, GrpImageTexture.h, GrpIndexBuffer.cpp, GrpIndexBuffer.h, GrpLightManager.cpp, GrpLightManager.h, GrpMarkInstance.cpp, GrpPixelShader.cpp, GrpRenderTargetTexture.cpp, GrpRenderTargetTexture.h, GrpScreen.cpp, GrpShadowTexture.cpp, GrpShadowTexture.h, GrpTextInstance.cpp, GrpTexture.cpp, GrpTexture.h, GrpVertexBuffer.cpp", "UserInterface; Packet.h, PythonApplicationModule.cpp, PythonCharacterManager.cpp, PythonCharacterManagerModule.cpp, PythonCharacterModule.cpp, PythonEffectModule.cpp, PythonItemModule.cpp, PythonNetworkStream.cpp, PythonNetworkStream.h, PythonNetworkStreamModule.cpp, PythonNetworkStreamPhaseGame.cpp, PythonNetworkStreamPhaseGameActor.cpp, PythonPlayer.cpp, PythonPlayerInput.cpp, PythonPlayerModule.cpp, PythonPlayerSettingsModule.cpp, PythonPlayerSettingsModule.h, PythonPlayerSkill.cpp, PythonTextTail.cpp, PythonTextTail.h", "DumpProto; ItemCSVReader.cpp", "Server/common; length.h, tables.h", "Server/db; ClientManagerLogin.cpp, ClientManagerPlayer.cpp, ProtoReader.cpp", "Server/game; affect.h, battle.cpp, char_battle.cpp, char.cpp, char.h, cmd_general.cpp, cmd_gm.cpp, cmd.cpp, config.cpp, config.h, constants.cpp, constants.h, input_login.cpp, packet.h, ProtoReader.cpp, questlua_pc.cpp, sectree_manager.cpp, sectree_manager.h"
#define ENABLE_DIRECTX9EX_UPDATE							// DirectX9Ex Update
#ifdef ENABLE_DIRECTX9EX_UPDATE
#undef D3DPOOL_MANAGED_EX_FIX
#define D3DPOOL_MANAGED_EX_FIX D3DPOOL_DEFAULT				// D3DPOOL_MANAGED yerine "D3DPOOL_MANAGED_EX_FIX" yazýldý 
#define ENABLE_PERFORMANCE_OPTIMIZATION						// Arkaplanda render ve sesi durdurur
#else
#define D3DPOOL_MANAGED_EX_FIX D3DPOOL_MANAGED
#endif
#define FPS_APPLICATON_DEVICE_LIMITATION 					// Belirli cihazlarda aþýrý yüksek FPS'ten kaynaklanan performans sorunlarýný önlemek için maksimum render FPS'ini sýnýrlayan sistemi etkinleþtirir;
#ifdef FPS_APPLICATON_DEVICE_LIMITATION
#define RENDER_MAX_FPS        120  					// Maksimum render FPS deðeri: cihaz performansýna göre üst sýnýr
#endif
#define ENABLE_ITEMSHOP
#ifdef ENABLE_ITEMSHOP									// Gerçek para veya premium para birimi karþýlýðýnda eþya, kostüm ve ek içerikler satýn alýnabilen oyun içi item market sistemini etkinleþtirir;	"UserInterface; PythonApplicationModule.cpp"
#define USE_ITEMSHOP_RENEWED						// Item market arayüzünün daha modern ve kategorize edilmiþ yenilenmiþ versiyonunu etkinleþtirir;	"UserInterface; PythonApplicationModule.cpp"
#endif
#define ENABLE_BIOLOGIST_SYSTEM								// Oyun içi biyolog NPC'sine belirli eþyalar teslim edilerek özel ödüller ve baþarýmlar kazanýlan biyolog sistemini etkinleþtirir;	"UserInterface; PythonApplicationModule.cpp"
#define ENABLE_YOHARA_SYSTEM          						// Yohara kýtasýna ait tüm içerikleri (yeni haritalar, SungMa mekaniði, þampiyon sistemi, pasif bonuslar ve 9. beceriler) etkinleþtiren çatý sistemdir;	"UserInterface; PythonApplicationModule.cpp", "Server/common; service.h"
#ifdef ENABLE_YOHARA_SYSTEM
#define ENABLE_CONQUEROR_LEVEL						// SungMa/Yohara sistemine ait þampiyon (conqueror) seviye mekanizmasýný etkinleþtirir; karakterin belirli bir eþiði geçmesini saðlar;	"UserInterface; Packet.h, PythonApplicationModule.cpp, PythonCharacterManager.cpp, PythonCharacterManagerModule.cpp, PythonCharacterModule.cpp, PythonEffectModule.cpp, PythonItemModule.cpp, PythonNetworkStream.cpp, PythonNetworkStream.h, PythonNetworkStreamModule.cpp, PythonNetworkStreamPhaseGame.cpp, PythonNetworkStreamPhaseGameActor.cpp, PythonPlayer.cpp, PythonPlayerInput.cpp, PythonPlayerModule.cpp, PythonPlayerSettingsModule.cpp, PythonPlayerSettingsModule.h, PythonPlayerSkill.cpp, PythonTextTail.cpp, PythonTextTail.h", "DumpProto; ItemCSVReader.cpp", "Server/common; length.h, tables.h", "Server/db; ClientManagerLogin.cpp, ClientManagerPlayer.cpp, ProtoReader.cpp", "Server/game; affect.h, battle.cpp, char_battle.cpp, char.cpp, char.h, cmd_general.cpp, cmd_gm.cpp, cmd.cpp, config.cpp, config.h, constants.cpp, constants.h, input_login.cpp, packet.h, ProtoReader.cpp, questlua_pc.cpp, sectree_manager.cpp, sectree_manager.h"
#define ENABLE_CONQUEROR_LEVEL_UPDATE				// Þampiyon seviyesinin gerçek zamanlý olarak güncellenmesini saðlayan anlýk yenileme mekanizmasýný etkinleþtirir;	"UserInterface; PythonApplicationModule.cpp"
#define ENABLE_PASSIVE_SYSTEM						// Karakter seviyesi ve Yohara ilerlemesine baðlý olarak otomatik kazanýlan pasif kalýntý (remnant) bonus sistemini etkinleþtirir;	"GameLib; ItemData.h", "UserInterface; GameType.h, InstanceBase.h, Packet.h, PythonApplicationModule.cpp, PythonCharacterManagerModule.cpp, PythonItemModule.cpp, PythonNetworkStreamPhaseGameItem.cpp, PythonPlayerSettingsModule.h", "DumpProto; ItemCSVReader.cpp", "Server/common; item_length.h, length.h, VnumHelper.h", "Server/db; ProtoReader.cpp", "Server/game; affect.h, char_horse.cpp, char_item.cpp, cmd_general.cpp, cmd.cpp, item.cpp, ProtoReader.cpp"
#define ENABLE_NINETH_SKILL							// Yohara içeriðiyle gelen 9. beceri slotu ve becerilerini etkinleþtirir;	"GameLib; ActorInstanceData.cpp", "UserInterface; GameType.h, InstanceBase.cpp, InstanceBase.h, InstanceBaseEffect.cpp, PythonApplicationModule.cpp, PythonCharacterModule.cpp, PythonPlayer.cpp", "Server/common; length.h", "Server/game; affect.h, char_affect.cpp, char_battle.cpp, char_item.cpp, char_skill.cpp, char.h, input_main.cpp, item_manager.cpp, skill.h"
#define ENABLE_PVP_BALANCE							// Yeni beceri animasyonlarý ve resmi PvP dengeleme mekanizmalarýný içeren sistemi etkinleþtirir;	"UserInterface; InstanceBase.cpp, InstanceBase.h, InstanceBaseEffect.cpp, InstanceBaseMovement.cpp, PythonApplicationModule.cpp", "Server/game; char_affect.cpp, char_battle.cpp, char_skill.cpp, char.cpp, char.h, input_main.cpp, skill.h"
#endif
#define ENABLE_DUNGEON_RENEWAL_SYSTEM      					// Zindan sistemini tümüyle yenileyen çatý yapýsýný etkinleþtirir; zindan bilgisi, takip penceresi ve geliþmiþ canlanma mekanizmalarýný kapsar;	"UserInterface; Locale_inc.h, PythonApplicationModule.cpp", "Server/common; service.h"
#ifdef ENABLE_DUNGEON_RENEWAL_SYSTEM
#define ENABLE_DUNGEON_INFO							// Zindan ilerleyiþi, süre ve hedef bilgilerini gösteren yeni zindan bilgi sistemi fonksiyonlarýný etkinleþtirir;	"UserInterface; Packet.h, PythonApplication.h, PythonApplicationModule.cpp, PythonNetworkStream.cpp, PythonNetworkStream.h, PythonNetworkStreamPhaseGame.cpp, StdAfx.h, UserInterface.cpp", "Server/common; tables.h", "Server/game; char_battle.cpp, char.cpp, char.h, cmd_gm.cpp, cmd.cpp, dungeon.cpp, input_login.cpp, input_main.cpp, input.h, main.cpp, packet_info.cpp, packet.h, questlua_dungeon.cpp, questlua.cpp, questlua.h"
#define __DUNGEON_INFO__               				// Oyuncunun zindan içindeyken can yenilenme (regen) sürecini yöneten yeni tip canlanma sistemini etkinleþtirir;	"EterPythonLib; PythonWindow.cpp", "UserInterface; PythonApplicationModule.cpp", "Server/common; tables.h", "Server/game; char_battle.cpp, char_manager.cpp, char_manager.h, char.cpp, char.h, cmd_general.cpp, cmd.cpp, constants.cpp, constants.h, input_login.cpp, questlua_dungeon.cpp"
#define ENABLE_NEW_DUNGEON_LIB						// Zindan yönetimi, ýþýnlanma noktalarý ve grup geçiþlerini destekleyen yeni zindan kütüphanesini etkinleþtirir;	"EterLib; GrpExpandedImageInstance.cpp, GrpExpandedImageInstance.h, GrpImageInstance.cpp, GrpImageInstance.h", "EterPythonLib; PythonWindow.cpp, PythonWindow.h, PythonWindowManagerModule.cpp", "UserInterface; PythonApplicationModule.cpp", "Server/common; length.h", "Server/game; dungeon.cpp, dungeon.h, questlua_dungeon.cpp, questlua_pc.cpp"
#define ENABLE_TRACK_WINDOW    						// Zindan içi hedef ve ilerleme bilgilerini gösteren takip (track) penceresini etkinleþtirir;	"EterPythonLib; PythonWindow.cpp, PythonWindow.h, PythonWindowManagerModule.cpp", "UserInterface; PythonApplicationModule.cpp, PythonNetworkStreamPhaseGame.cpp, PythonSystem.cpp, PythonSystem.h, PythonSystemModule.cpp", "Server/game; char.cpp, char.h, cmd_general.cpp, cmd.cpp, questlua_dungeon.cpp"
#define ENABLE_ULTIMATE_REGEN               		// Zindan içinde özel koþullar altýnda grup üyelerinin canlanmasýný yöneten geliþmiþ regen sistemini etkinleþtirir;	"UserInterface; InstanceBase.cpp, Packet.h, PythonApplicationModule.cpp, PythonCharacterManager.cpp, PythonCharacterManager.h, PythonMiniMap.cpp, PythonMiniMap.h, PythonMiniMapModule.cpp, PythonNetworkStreamPhaseGame.cpp, PythonPlayer.cpp, PythonPlayer.h, PythonPlayerModule.cpp", "Server/game; battle.cpp, char_battle.cpp, cmd_gm.cpp, input_db.cpp, input_p2p.cpp, input.h, main.cpp, packet_info.cpp, packet.h, regen.cpp, sectree_manager.cpp, sectree_manager.h"
#endif
#define ENABLE_DUNGEON_MAPS_SYSTEM      					// Yohara ve resmi içeriklerden gelen tüm yeni zindan ve harita altyapýsýný etkinleþtiren çatý tanýmýdýr;	"UserInterface; Locale_inc.h, PythonApplicationModule.cpp", "Server/common; service.h"
#ifdef ENABLE_DUNGEON_MAPS_SYSTEM
	// Yohara Zindanlarý
#define ENABLE_SUNG_MAHI_TOWER    					// Yohara içeriðinin ana zindaný olan SungMa Ýstilasý (Sung Mahi Tower) haritasýný etkinleþtirir;	"EterLib; GrpTextInstance.cpp, GrpTextInstance.h", "EterPythonLib; PythonWindow.cpp, PythonWindow.h, PythonWindowManagerModule.cpp", "UserInterface; InstanceBase.h, PythonApplicationModule.cpp, PythonCharacterModule.cpp", "Server/common; length.h", "Server/game; affect.h, char_battle.cpp, char_item.cpp, char_manager.cpp, char_resist.cpp, char_skill.cpp, char_state.cpp, char.cpp, char.h, cmd_general.cpp, dungeon.cpp, dungeon.h, questlua_affect.cpp, questlua_dungeon.cpp, questlua_pc.cpp, questmanager.cpp, questmanager.h, regen.cpp"
#define ENABLE_WHITE_DRAGON       					// Kuzey Rüzgarý Derinlikleri (Alastor / White Dragon) zindan haritasýný etkinleþtirir;	"UserInterface; Locale_inc.h", "Server/common; length.h, service.h", "Server/game; char_battle.cpp, char.cpp, main.cpp, questlua_whitedragon.cpp, questlua.cpp, questlua.h, WhiteDragon.cpp, WhiteDragon.h"
#ifdef ENABLE_WHITE_DRAGON
	//#define ENABLE_WHITE_DRAGON_EX 			// Alastor canavar ve event uzantý mekaniklerini etkinleþtirir (kapalý);	"Server/game; WhiteDragon.cpp"
#endif
#define ENABLE_QUEEN_NETHIS       					// Yýlan Tapýnaðý (Kraliçe Nethis / Snake Lair) zindan haritasýný etkinleþtirir;	"UserInterface; InstanceBase.h, Packet.h, PythonApplicationModule.cpp, PythonCharacterModule.cpp, PythonNetworkStreamPhaseGameItem.cpp, PythonPlayerSettingsModule.h", "Server/common; length.h", "Server/game; affect.h, battle.cpp, char_battle.cpp, char_item.cpp, char_skill.cpp, char.cpp, char.h, cmd_general.cpp, input_main.cpp, main.cpp, party.cpp, questlua_snakelair.cpp, questlua.cpp, questlua.h, SnakeLair.cpp, SnakeLair.h"
#define ENABLE_MELEY_LAIR_DUNGEON     				// Meley'in Ýni (Meley's Lair) lonca zindan haritasýný etkinleþtirir;	"UserInterface; InstanceBase.h, InstanceBaseEffect.cpp, Locale_inc.h, PythonApplicationModule.cpp, PythonCharacterModule.cpp, PythonPlayerSettingsModule.h", "Server/game; affect.h, char_battle.cpp, char_state.cpp, char.cpp, char.h, quest.h, questlua_npc.cpp, questmanager.cpp, questmanager.h, questnpc.cpp, questnpc.h"
#ifdef ENABLE_MELEY_LAIR_DUNGEON
#define MELEY_LAIR_DUNGEON_STATUE 6230 		// Meley'in Ýni içerisinde kullanýlan ana heykel (statue) NPC vnum'u
#endif
#define ENABLE_ZODIAC_MISSION						// Zodyak Tapýnaðý görev ve zindan sistemini etkinleþtirir;	"UserInterface; InstanceBase.h, Packet.h, PythonApplicationModule.cpp, PythonCharacterManagerModule.cpp, PythonNetworkStreamCommand.cpp, PythonNetworkStreamPhaseGameItem.cpp, PythonPlayerSettingsModule.h", "Server/common; length.h", "Server/game; char_battle.cpp, char_item.cpp, char_skill.cpp, char_state.cpp, char.cpp, char.h, cmd_general.cpp, cmd.cpp, dungeon.cpp, dungeon.h, input_login.cpp, packet.h, questlua_game.cpp, questlua_npc.cpp, questlua.cpp, questlua.h, shop.cpp"
#define ENABLE_DEFENSAWESHIP             			// Resmi sürümdeki Gemi Savunma Zindaný'ný (Hydra Dungeon) etkinleþtirir;	"GameLib; ActorInstance.cpp", "UserInterface; InstanceBase.cpp, InstanceBase.h, PythonApplicationModule.cpp"
#define ENABLE_OCHAO_TEMPLE_SYSTEM   				// Ochao Tapýnaðý ve Büyülü Orman zindan sistemlerini etkinleþtirir;	"UserInterface; InstanceBase.h, Packet.h, PythonApplicationModule.cpp, PythonCharacterManagerModule.cpp, PythonNetworkStreamPhaseGameItem.cpp, PythonPlayerSettingsModule.h", "Server/common; length.h, service.h", "Server/game; char_battle.cpp, char_skill.cpp, main.cpp, questlua_global.cpp, questlua.cpp, questlua.h, sectree_manager.cpp, sectree_manager.h, skill.h"
#endif
#define INSIDE_RENDER
#define ENABLE_BATTLE_PASS                      			// Görevler tamamlandýkça ilerleyen ve ödüller kazandýran resmi savaþ bileti (battle pass) sistemini etkinleþtirir;	"UserInterface; PythonApplicationModule.cpp", "Server/common; length.h, service.h", "Server/game; affect.h, char_affect.cpp, char_battle.cpp, char_item.cpp, char_pass_premium.cpp, char_pass.cpp, char.cpp, char.h, cmd_general.cpp, cmd.cpp, fishing.cpp, input_login.cpp, input_main.cpp, questlua_pc.cpp"
#define ENABLE_WHISPER_CLOSE_SHORTCUT        				// Özel mesaj (whisper) penceresini klavye kýsayoluyla hýzlýca kapatmayý saðlar;	"UserInterface; PythonApplicationModule.cpp"
#define ENABLE_AFFECT_BUFF_REMOVE            				// Karakter üzerindeki aktif buff/efektlerin oyuncu tarafýndan manuel olarak kaldýrýlabilmesini saðlar;	"UserInterface; PythonApplicationModule.cpp", "Server/game; cmd_general.cpp, cmd.cpp"
#define LINK_IN_CHAT 										// Sohbet panelinde týklanabilir öðe, NPC ve konum baðlantýlarý (hyperlink) eklenmesini etkinleþtirir;	"UserInterface; PythonApplicationModule.cpp, PythonChatModule.cpp"
#define ENABLE_REMOTE_SHOP_SYSTEM							// Karakterin fiziksel olarak dükkanýn yanýnda bulunmadan uzaktan alýþveriþ yapmasýný saðlayan uzak market sistemini etkinleþtirir;	"UserInterface; PythonApplicationModule.cpp", "Server/game; cmd_general.cpp, cmd.cpp"
#define NAMECOLOR_BOSS_CLIENT								// Boss canavarlarýnýn isim rengini diðer canavarlardan farklý olarak özel bir renkle göstererek kolayca tanýnabilmelerini saðlar;	"UserInterface; InstanceBase.cpp, InstanceBase.h, InstanceBaseEffect.cpp, PythonApplicationModule.cpp, PythonCharacterManagerModule.cpp, PythonMiniMap.cpp, PythonMiniMap.h, PythonPlayerSettingsModule.h"
#define ENABLE_ADVANCED_GAME_OPTIONS						// Standart ayarlar menüsünün ötesinde oyun davranýþýný ince ayarlamayý saðlayan geliþmiþ oyun seçenekleri panelini etkinleþtirir;	"UserInterface; PythonApplicationModule.cpp"
#define ENABLE_EQUIPMENT_HAND_EFFECT						// Karakterin sað ve sol eline takýlan ekipmanlar için el üzerinde görünen özel efekt desteðini saðlar;	"UserInterface; InstanceBase.h, PythonApplicationModule.cpp, PythonCharacterModule.cpp, PythonPlayerSettingsModule.h", "Server/game; affect.h, char_affect.cpp, char_item.cpp, item.cpp, unique_item.h"
#define ENABLE_RESP_SYSTEM									// Boss ve metin taþlarý için gerçek zamanlý yeniden doðma (respawn) takibini ve bildirimini saðlayan spawn yönetim sistemini etkinleþtirir;	"UserInterface; Packet.h, PythonApplicationModule.cpp, PythonNetworkStream.cpp, PythonNetworkStream.h, PythonNetworkStreamModule.cpp, PythonNetworkStreamPhaseGame.cpp", "Server/common; length.h", "Server/game; char_battle.cpp, char.cpp, char.h, constants.cpp, constants.h, input_login.cpp, input_main.cpp, input.h, main.cpp, packet_info.cpp, packet.h, RealTimeRegen.cpp, regen.cpp, regen.h, resp_manager.cpp"
#define ENABLE_COLLECT_WINDOW								// Koleksiyon sistemine ait GUI (pencere) arayüzünü aktif eder; toplanan eþya ve baþarýmlarý listeler;	"UserInterface; Packet.h, PythonApplicationModule.cpp, PythonBackgroundModule.cpp, PythonEventManagerMoudle.cpp, PythonNetworkStream.cpp, PythonNetworkStream.h, PythonNetworkStreamPhaseGame.cpp", "Server/game; affect.h, char_item.cpp, char.cpp, char.h, cmd_general.cpp, cmd.cpp, input_main.cpp, packet.h, quest.h, questlua_pc.cpp, questmanager.cpp, questmanager.h, questnpc.cpp, questnpc.h"
#define ENABLE_COLLECTIONS_SYSTEM							// Belirli eþyalarýn toplanmasý karþýlýðýnda ödüller sunan koleksiyon (albüm) sisteminin tamamýný etkinleþtirir;	"GameLib; ItemData.h", "UserInterface; PythonApplicationModule.cpp, PythonItemModule.cpp"
#define ENABLE_NEW_ITEM_TYPE_GACHA							// Geleneksel sandýk yerine çalýþan gacha (kapsül/çark) sistemi için yeni öðe tipini etkinleþtirir; özel açýlýþ animasyonu ve ödül tablosu destekler;	"GameLib; ItemData.h", "UserInterface; PythonItemModule.cpp", "DumpProto; ItemCSVReader.cpp", "Server/common; item_length.h", "Server/db; ProtoReader.cpp", "Server/game; char_item.cpp, item_manager.cpp, item.cpp, ProtoReader.cpp"
#define ENABLE_GAYA_SYSTEM                         			// Yohara içeriðine ait Gaya para birimi, Gaya NPC'leri ve Gaya tabanlý takas mekaniklerini etkinleþtirir;	"UserInterface; Packet.h, PythonApplicationModule.cpp, PythonCubeRenewal.cpp, PythonNetworkStreamPhaseGame.cpp, PythonPlayerModule.cpp", "Server/common; length.h, service.h, tables.h", "Server/db; ClientManagerPlayer.cpp", "Server/game; char_item.cpp, char.cpp, char.h, cmd_gm.cpp, cube_renewal.cpp, cube_renewal.h, input_db.cpp, packet.h, questlua_pc.cpp"
#define ENABLE_RANKING										// Oyuncularýn PvP, seviye veya baþka kriterlere göre sýralandýðý liderlik tablosu (ranking) sistemini etkinleþtirir;	"UserInterface; Packet.h, PythonApplicationModule.cpp, PythonNetworkStream.cpp, PythonNetworkStream.h, PythonNetworkStreamPhaseGame.cpp", "Server/common; length.h, tables.h", "Server/db; ClientManagerPlayer.cpp", "Server/game; char_battle.cpp, char_item.cpp, char.cpp, char.h, cmd_general.cpp, cmd.cpp, fishing.cpp, packet.h, questlua_pc.cpp, switchbot_manager.cpp"
#define ENABLE_MAGIC_REDUCTION_SYSTEM						// Büyü direnci ve büyü bozma bonusu attribute tiplerini etkinleþtirir; PvP ve PvM dengesi için kullanýlýr;	"GameLib; ItemData.h", "UserInterface; GameType.cpp, Packet.h, PythonApplicationModule.cpp, PythonItemModule.cpp", "DumpProto; ItemCSVReader.cpp", "Server/common; length.h, service.h", "Server/db; ProtoReader.cpp", "Server/game; char_battle.cpp, char_skill.cpp, char.cpp, char.h, cmd_general.cpp, cmd_gm.cpp, constants.cpp, ProtoReader.cpp"
#define ENABLE_NEW_BONUS_SYSTEM								// Patronlara (boss) karþý yeni bonus attribute türlerini etkinleþtirir; özelleþtirilmiþ PvE savaþ bonuslarý ekler;	"GameLib; ItemData.h", "UserInterface; GameType.cpp, Packet.h, PythonApplicationModule.cpp, PythonItemModule.cpp, PythonPlayerModule.cpp", "DumpProto; ItemCSVReader.cpp", "Server/common; length.h", "Server/db; ProtoReader.cpp", "Server/game; battle.cpp, char.cpp, char.h, constants.cpp, ProtoReader.cpp"
#define ENABLE_AVG_PVM										// Yüksek ortalama hasar bonusu (avg PvM) attribute tipini etkinleþtirir; canavar türüne göre kademeli hasar artýþý saðlar;	"GameLib; ItemData.h", "UserInterface; GameType.cpp, Packet.h, PythonApplicationModule.cpp, PythonItemModule.cpp, PythonPlayerModule.cpp", "DumpProto; ItemCSVReader.cpp", "Server/common; length.h, service.h", "Server/db; ProtoReader.cpp", "Server/game; char_battle.cpp, char.cpp, char.h, cmd_gm.cpp, constants.cpp, item_addon.cpp, ProtoReader.cpp"
#define ENABLE_EXPRESSING_EMOTION							// Yeni dans animasyonlarý ve emoji ifade sistemi; karakterin çeþitli duygusal hareketler sergileyebilmesini saðlar;	"UserInterface; PythonApplicationModule.cpp"
#define ENABLE_STATUS_UP_RENEWAL							// Güç, çeviklik gibi temel statü puanlarýný hýzlýca artýran geliþtirilmiþ statü yükseltme arayüzünü etkinleþtirir;	"UserInterface; PythonApplicationModule.cpp", "Server/game; cmd_general.cpp"
#define ENABLE_BINARY_SERVERINFO							// Sunucu IP, port ve kanal bilgilerinin Python/config dosyasý yerine doðrudan binary üzerinden güvenli þekilde iletilmesini saðlar;	"UserInterface; PythonNetworkStreamModule.cpp"
#define ENABLE_TITLE_SYSTEM									// Resmi sürümdeki gibi baþarým veya görev tamamlama karþýlýðýnda kazanýlan ve karakter adýnýn yanýnda görünen unvan (title) sistemini etkinleþtirir;	"GameLib; ItemData.cpp, ItemData.h", "UserInterface; InstanceBase.cpp, InstanceBase.h, InstanceBaseEffect.cpp, PythonApplicationModule.cpp, PythonItemModule.cpp, PythonNetworkStreamPhaseGameItem.cpp", "DumpProto; ItemCSVReader.cpp", "Server/common; item_length.h", "Server/db; ProtoReader.cpp", "Server/game; char_item.cpp, char.cpp, cmd_general.cpp, cmd.cpp, ProtoReader.cpp"
#ifdef _DEBUG
#define ENABLE_UI_DEBUG_WINDOW								// Oyun içinde çeþitli UI bileþenlerinin koordinat, boyut ve render bilgilerini görüntülemek için geliþtirici debug penceresini etkinleþtirir;	"EterPythonLib; PythonGraphic.cpp, PythonGraphic.h, PythonWindow.cpp", "UserInterface; GameType.cpp, PythonApplicationModule.cpp"
#endif
	/*#define ENABLE_WOLFMAN_CHARACTER							// Lycan (Wolfman/Kurt Adam) oyuncu karakterini etkinleþtirir; Ama tam ekli deðil açmayýn.	"GameLib; ItemData.h", "UserInterface; GameType.h, InstanceBase.cpp, InstanceBase.h, InstanceBaseEffect.cpp, Locale_inc.h, PythonApplicationModule.cpp, PythonItemModule.cpp, PythonPlayer.cpp, PythonPlayerSettingsModule.h", "DumpProto; ItemCSVReader.cpp", "Server/common; length.h", "Server/game; battle.cpp, BlueDragon_Skill.h, BotPlayer.cpp, char_affect.cpp, char_manager.cpp, char_skill.cpp, char.cpp, cmd_general.cpp, cmd_gm.cpp, constants.cpp, motion.cpp, ProtoReader.cpp, questlua_pc.cpp, skill.cpp, skill.h"
	#ifdef ENABLE_WOLFMAN_CHARACTER
		//#define DISABLE_WOLFMAN_ON_CREATE					// Lycan (Wolfman) karakterini python üzerinden açma/kapatmayý etkinleþtirir;
#endif*/
#define ENABLE_EVENT_SYSTEM									// Belirli zaman dilimlerinde veya GM komutuyla otomatik baþlatýlan ve sonlandýrýlan etkinlikleri yöneten kapsamlý etkinlik sistemi çatýsýný etkinleþtirir;	"UserInterface; Locale_inc.h, Packet.h, PythonApplicationModule.cpp, PythonNetworkStream.cpp, PythonNetworkStream.h, PythonNetworkStreamPhaseGame.cpp, StdAfx.h, UserInterface.cpp", "Server/common; service.h", "Server/game; auto_event_manager.cpp, char_manager.cpp, input_login.cpp, input_p2p.cpp, input.h, item_manager.cpp, main.cpp, packet_info.cpp, packet.h, questlua_game.cpp, questmanager.cpp"
#ifdef ENABLE_EVENT_SYSTEM
#define ENABLE_MINI_GAME_OKEY						// Türk okey kartlarýna dayalý Rumi mini oyun sistemini etkinleþtirir;	"UserInterface; PythonApplicationModule.cpp, PythonGameEventManager.cpp, PythonGameEventManager.h, PythonGameEventManagerModule.cpp, PythonNetworkStreamCommand.cpp"
#define ENABLE_EVENT_BANNER_FLAG					// Aktif etkinliklerin oyun dünyasýnda banner/bayrak olarak görselleþtirilmesini ve minimap üzerinde iþaretlenmesini saðlar;	"UserInterface; InstanceBase.cpp, InstanceBase.h, InstanceBaseEffect.cpp, PythonMiniMap.cpp, PythonTextTail.cpp", "Server/game; char_manager.cpp, char_manager.h, cmd_gm.cpp, cmd.cpp, questmanager.cpp"
#define ENABLE_SOUL_ROULETTE_SYSTEM					// Kan Ritüeli (Soul Roulette) çark mini oyununu etkinleþtirir; oyuncular rulet döndürerek özel ödüller kazanýr;	"UserInterface; GameType.h, Packet.h, PythonApplicationModule.cpp, PythonNetworkStream.cpp, PythonNetworkStream.h, PythonNetworkStreamModule.cpp, PythonNetworkStreamPhaseGame.cpp, PythonPlayerModule.cpp", "Server/common; length.h, tables.h", "Server/db; ClientManagerPlayer.cpp", "Server/game; char.cpp, char.h, cmd_gm.cpp, cmd.cpp, cmd.h, input_login.cpp, input_main.cpp, input.h, log.cpp, log.h, main.cpp, packet_info.cpp, packet.h, questlua_pc.cpp, questmanager.cpp, soulroulette.cpp, soulroulette.h"
#define ENABLE_FISH_GAME                    		// Resmi sunuculardaki yeni balýk tutma mini oyununu etkinleþtirir; özel arayüz ve animasyonlar içerir;	"EterLib; GrpExpandedImageInstance.h", "EterPythonLib; PythonWindow.cpp, PythonWindow.h, PythonWindowManagerModule.cpp", "UserInterface; PythonApplication.h, PythonApplicationCursor.cpp, PythonApplicationModule.cpp"
#define ENABLE_FISH_EVENT_SYSTEM					// Balýk tutma mini oyununa ait tüm að paketi ve arayüz entegrasyonunu etkinleþtirir;	"EterPythonLib; PythonGridSlotWindow.cpp, PythonGridSlotWindow.h, PythonSlotWindow.cpp, PythonSlotWindow.h, PythonWindowManager.h, PythonWindowManagerModule.cpp", "UserInterface; GameType.h, Packet.h, PythonApplicationModule.cpp, PythonNetworkStream.cpp, PythonNetworkStream.h, PythonNetworkStreamModule.cpp, PythonNetworkStreamPhaseGame.cpp, PythonNetworkStreamPhaseGameItem.cpp, PythonPlayerModule.cpp"
#define ENABLE_MINI_GAME							// Resmi sunuculardaki yeni mini oyunlar için çatý altyapýsýný etkinleþtirir; farklý mini oyun türlerini destekler;	"EterPythonLib; PythonSlotWindow.cpp, PythonSlotWindow.h, PythonWindowManagerModule.cpp", "UserInterface; Packet.h, PythonApplicationModule.cpp, PythonGameEventManager.cpp, PythonGameEventManager.h, PythonGameEventManagerModule.cpp, PythonNetworkStream.cpp, PythonNetworkStream.h, PythonNetworkStreamCommand.cpp, PythonNetworkStreamModule.cpp, PythonNetworkStreamPhaseGame.cpp", "Server/game; char.cpp, char.h, cmd_gm.cpp, cmd.cpp, input_login.cpp, input_main.cpp, item_manager.cpp, main.cpp, minigame_attendance.cpp, minigame.h, packet_info.cpp, packet.h, questlua_game.cpp, questmanager.cpp"
#define ENABLE_ATTENDANCE_EVENT						// Canavar Avý etkinliðini (Monster Attendance/Hunt Event) ve günlük katýlým takip ile ödül mekanizmasýný etkinleþtirir;	"UserInterface; InstanceBase.h, Packet.h, PythonApplicationModule.cpp, PythonCharacterModule.cpp, PythonNetworkStream.cpp, PythonNetworkStream.h, PythonNetworkStreamModule.cpp, PythonNetworkStreamPhaseGame.cpp, PythonPlayer.cpp, PythonPlayer.h, PythonPlayerModule.cpp", "Server/game; affect.h, battle.cpp, char_battle.cpp, char_manager.cpp, char_resist.cpp, char.cpp, char.h, cmd_gm.cpp, cmd.cpp, input_db.cpp, input_login.cpp, input_main.cpp, main.cpp, packet_info.cpp, packet.h, questlua_game.cpp, questmanager.cpp"
#define ENABLE_MINI_GAME_CATCH_KING					// Kralý Yakala (Catch the King) kart mini oyununu etkinleþtirir;	"UserInterface; Packet.h, PythonApplicationModule.cpp, PythonNetworkStream.cpp, PythonNetworkStream.h, PythonNetworkStreamModule.cpp, PythonNetworkStreamPhaseGame.cpp", "Server/game; char.cpp, char.h, cmd_gm.cpp, cmd.cpp, input_login.cpp, input_main.cpp, item_manager.cpp, main.cpp, minigame_attendance.cpp, minigame.h, packet_info.cpp, packet.h, questlua_game.cpp, questmanager.cpp"
#define ENABLE_HALLOWEEN_EVENT_SYSTEM				// Cadýlar Bayramý etkinlik sistemini etkinleþtirir; özel haritalar, kostümler ve mevsimsel içerikler sunar;	"UserInterface; Packet.h, PythonApplicationModule.cpp", "Server/common; tables.h", "Server/db; ClientManagerPlayer.cpp", "Server/game; char_item.cpp, char.cpp, char.h, cmd_general.cpp, cmd.cpp, input_login.cpp"
#define ENABLE_STONE_EVENT							// Metin taþý kesme/sýralama etkinlik sistemini etkinleþtirir; oyuncular metin taþý öldürme yarýþmasýna katýlýr;	"UserInterface; Packet.h, PythonApplicationModule.cpp, PythonNetworkStream.cpp, PythonNetworkStream.h, PythonNetworkStreamPhaseGame.cpp", "Server/game; char_battle.cpp, input_login.cpp, input_p2p.cpp, input.h, main.cpp, packet_info.cpp, packet.h, stone_event.cpp"
#define ENABLE_SOCCER_BALL_EVENT					// Futbol Topu etkinliðini ve ilgili oyun mekaniklerini etkinleþtirir;	"UserInterface; PythonApplicationModule.cpp", "Server/game; cmd_general.cpp, cmd.cpp"
#define ENABLE_WORD_GAME_EVENT						// Kelime oyunu etkinliðini etkinleþtirir; oyuncular sohbet üzerinden kelime bulmacalarý çözer;	"UserInterface; PythonApplicationModule.cpp", "Server/game; cmd_general.cpp, cmd.cpp"
#endif
/*** TAMAMLANMAMIÞ SÝSTEMLER (YAKINDA) ***/
#define ENABLE_GUILDRENEWAL_SYSTEM							// Lonca sistemini baþtan aþaðýya yenileyen; lonca logosu, seviye, banka, savaþ ve arazi yönetimini modernize eden çekirdek sistemi etkinleþtirir;	"UserInterface; Locale_inc.h, Packet.h, PythonApplicationModule.cpp, PythonGuild.cpp, PythonItemModule.cpp", "Server/common; service.h"
#ifdef ENABLE_GUILDRENEWAL_SYSTEM	
#define ENABLE_GUILD_MARK_RENEWAL					// Lonca logo (mark) yükleme, güncelleme ve sunucuya gönderme iþ akýþýný yenilenmiþ versiyonla deðiþtirir;	"UserInterface; PythonApplicationModule.cpp"
#define ENABLE_SECOND_GUILDRENEWAL_SYSTEM			// Ek modüllerle geniþletilmiþ ikinci lonca yenileme katmanýný etkinleþtirir;	"UserInterface; PythonApplicationModule.cpp"
#define ENABLE_NEW_WAR_OPTIONS						// Tur sayýsý, puan limiti ve süre bazlý ayarlar içeren modern lonca savaþý seçeneklerini etkinleþtirir;	"UserInterface; PythonApplicationModule.cpp"
#define ENABLE_EXTENDED_GUILD_LEVEL					// Lonca seviye kapasitesini 20'den 30'a yükselterek daha büyük loncalarýn daha fazla özellik açmasýný saðlar;	"UserInterface; PythonApplicationModule.cpp"
//#define ENABLE_MEDAL_OF_HONOR						// Lonca ekonomisi için yeni bir para birimi olan Onur Madalyasý sistemini etkinleþtirir (kapalý);	"UserInterface; PythonApplicationModule.cpp"
#define ENABLE_GUILD_DONATE_ATTENDANCE				// Günlük lonca baðýþlarýný ve katýlým puaný takip sistemini etkinleþtirir;	"UserInterface; PythonApplicationModule.cpp"
#define ENABLE_GUILD_WAR_SCORE						// Lonca savaþý istatistiklerini detaylý skor ekranýnda gösteren sistemi etkinleþtirir;	"UserInterface; PythonApplicationModule.cpp"
#define ENABLE_GUILD_LAND_INFO						// Lonca arazilerine ait detaylý bilgi (konuþma, kira, sahiplik) arayüzünü etkinleþtirir;	"UserInterface; PythonApplicationModule.cpp"
#define ENABLE_GUILDBANK_LOG						// Lonca bankasýna yapýlan tüm iþlemlerin günlük kayýt sistemini etkinleþtirir;	"UserInterface; PythonApplicationModule.cpp"
#define ENABLE_EXTENDED_RENEWAL_FEATURES			// Lonca lideri devretme ve arazi silme gibi ek yönetim özelliklerini etkinleþtirir;	"UserInterface; PythonApplicationModule.cpp"
#define ENABLE_GUILDWAR_BUTTON						// Lonca savaþýna katýlým için arayüze eriþim düðmesi ekler;	"UserInterface; PythonApplicationModule.cpp"
//#define ENABLE_GUILD_REQUEST						// Lonca baþvuru altyapýsý (eksik modüller nedeniyle devre dýþý);	"UserInterface; PythonApplicationModule.cpp"
#define ENABLE_NEW_WORLD_GUILDRENEWAL				// Geliþmiþ lonca yenileme/güncelleme sistemi (sunucu tarafý eksik modüller);	"UserInterface; PythonApplicationModule.cpp"
//#define ENABLE_GUILD_RANKING						// Loncalar arasý sýralama sistemi (tam entegre edilmediði için kapalý);
//#define ENABLE_GUILDSTORAGE_SYSTEM     			// Loncanýn ortak deposu: üyelerin paylaþýmlý eþya deposu sistemi (kapalý);
#endif
/*** TAMAMLANMAMIÞ SÝSTEMLER (YAKINDA) ***/

/*** DÜZELTMELER ***/
#define __ENABLE_STEALTH_FIX__								// Görünmezlik modundan çýkýldýðýnda karakter üzerinde kalan veya yanlýþ görüntülenen efektlerin temizlenmesini saðlayan düzeltme;	"EffectLib; EffectInstance.cpp, EffectManager.cpp, EffectManager.h", "EterLib; GrpObjectInstance.cpp, GrpObjectInstance.h", "GameLib; ActorInstanceAttach.cpp", "UserInterface; InstanceBaseEffect.cpp"
#define MULTIPLE_DAMAGE_DISPLAY_SYSTEM						// Ayný anda birden fazla hasar deðerinin üst üste gelmeden düzgün biçimde ekranda gösterilmesini saðlayan çoklu hasar görüntüleme düzeltmesi;	"UserInterface; PythonNetworkStreamPhaseGame.cpp", "Server/game; char_battle.cpp"
#define ENABLE_DAMAGE_EFFECT_ACCUMULATION_FIX				// Hýzlý saldýrýlarda hasar efektlerinin birikip animasyon sorununa yol açmasýný önleyen birikme düzeltmesi;	"UserInterface; InstanceBase.h, InstanceBaseEffect.cpp, Packet.h", "Server/game; char_battle.cpp, packet.h"
#define ENABLE_BOSS_FALLING_FIX								// Boss canavarlarýnýn yüzey tespiti hatasý nedeniyle zeminden aþaðý düþmesi veya harita dýþýna kaymasý sorununu giderer;	"GameLib; ActorInstanceBattle.cpp"
#define ENABLE_CLIENT_UNEXPECTED_CLOSE_FIX					// Ýstemcinin syserr kaydý býrakmadan sessizce kapanmasýna yol açan bazý bellek ve kaynak yönetimi hatalarýný düzeltir;	"PRTerrainLib; TextureSet.cpp"
#define ENABLE_INVISIBLE_MODE_EFFECT_FIX					// Görünmezlik modundan çýkýldýðýnda karakter üzerinde hatalý kalan görsel efektlerin temizlenmesini saðlar;	"UserInterface; InstanceBaseEffect.cpp"
#define ENABLE_LENS_RENDER_FIX								// Lens flare (ýþýk hüzmesi) ve kamera zoom ile ilgili yanlýþ render problemlerini gidererek ekran dýþýna taþan görsel hatalarý düzeltir;	"EterLib; LensFlare.cpp"
#define ENABLE_AUTO_ATTACK_ARCHER_NINJA_FIX     			// Okçu ve ninja sýnýflarýna özgü otomatik saldýrý mekanizmasýnda oluþan hedefleme ve animasyon hatalarýný giderir;	"UserInterface; PythonPlayerInput.cpp"
#define ENABLE_TEXTURE_SCALE_FIX                			// %100 ölçek dýþýndaki çözünürlük veya UI ölçekleme kaynaklý texture hizalama ve boyutlandýrma hatalarýný düzeltir;	"EterGrnLib; Thing.cpp, Thing.h"
#define ENABLE_TIMESTAMPED_EXCEPTION_DUMP   				// Her bir istisna (exception) için "errorlog" klasörüne DD-MM-YYYY_HH-MM-SS biçiminde zaman damgalý hata döküm dosyasý yazar ve errorlog.exe'yi çalýþtýrýr;	"EterBase; error.cpp"
#define ENABLE_NEW_STOP_ON_BLOCK    						// Engelleyici (ATTRIBUTE_BLOCK) tespit edildiðinde mevcut BlockMovement() çaðrýsýna ek olarak NEW_Stop() fonksiyonunu çaðýrýr; çarpýþma sonrasý hareket durdurma iyileþtirmesi;	"UserInterface; InstanceBaseBattle.cpp"
#define ENABLE_ABORT_TRACEBACK_WITH_LINE   					// Abort sýrasýnda Python traceback bilgilerini (dosya adý, fonksiyon adý, satýr numarasý) loglar; kullanýlmazsa standart abort davranýþý korunur;	"UserInterface; PythonApplication.cpp"
#define ENABLE_EXTENDED_SYSERR								// Standart syserr.txt günlüðünü geniþleterek daha fazla hata baðlamý, zaman damgasý ve yýðýn izleme bilgisi kaydeden geliþmiþ hata kayýt sistemini etkinleþtirir;	"EterBase; Debug.cpp"
#define DISABLE_BACKGROUND_DARKENING						// Oyun arka planýnda menü veya diyalog açýldýðýnda uygulanan ekran karartma efektini devre dýþý býrakýr;
// #define ENABLE_SYSERR_BY_PID								// [Debug.cpp] syserr.txt yerine her iþlem için ayrý syserr-{pid}.txt oluþturur (kapalý);
#define PAKET_ESITLEME										// [EKSIK], [BOYUT FARKI], [TIP FARKI], [ISIM FARKI], [TIP+ISIM FARKI], kategorilerinde paketleri inceleyerek eþler
#ifdef PAKET_ESITLEME
	#define SPacketCGPetHatch_Paketi CItemData::PET_NAME_MAX_SIZE
	#define TPacketGCCharacterUpdate_Paketi ESkillColorLength::MAX_SKILL_COUNT+MAX_BUFF_COUNT
	#define TPacketGCCharacterAdditionalInfo_Paketi ESkillColorLength::MAX_SKILL_COUNT + MAX_BUFF_COUNT
	#define ID_MAX_NUM_LOGIN_MAX_LEN_Paketleri ID_MAX_NUM

#endif
/*** DÜZELTMELER ***/

/*<----Bilgilendirme---->*/
// Eðer bir kostüm sistemi devre dýþý býrakýlýrsa, uiscript içindeki costumewindow.py dosyasýný düzenlemeniz gerekir (CostumeSlot'u yorum satýrý haline getirin)

/*
@#GENEL MAKROLAR
#define __OBSOLETE__								// Kullanýlmayan ve gereksiz kodlar kaldýrýldý
#define __UNIMPLEMENTED__							// Uygulanacak yeni þeylerin taslaklarý
#define __UNIMPLEMENTED_EXTEND__					// Uygulanacak yeni þeylerin geniþletilmiþ taslaklarý
*/

/*
#@@Genel Olarak
@warme601: syserr.txt gibi hata dosyalarý ile birlikte geliþmiþ daðýtým için release sürümünü kullanýn.
*/
