import uiScriptLocale

IMG_DIR = "d:/ymir work/ui/game/advanced_game_options/"

TITLE_IMAGE_TEXT_X = 5
TITLE_IMAGE_TEXT_Y = 4

OPTION_START_X = 17
SLIDER_POSITION_X = 30

SLIDER_START_Y = 50
BUTTON_START_Y = 33
BUTTON_NEXT_Y = 20

RADIO_BUTTON_RANGE_X = 80
TOGGLE_BUTTON_RANGE_X = 65

RADIO_BUTTON_TEXT_X = 25
TOGGLE_BUTTON_TEXT_X = 45

SMALL_OPTION_HEIGHT = 65
NORMAL_OPTION_HEIGHT = 80
SLIDER_OPTION_HEIGHT = 65

PRIMARY_COLOR = 0xffd0c2b7
SECONDARY_COLOR = 0xff9f9892

window = {
	"name" : "GameOptionDialog",
	# Dont touch these lines!
	"style" : (),
	"x" : 222,
	"y" :1,
	"width" : 371,
	"height" : 404,
	# Dont touch these lines!
	"children" :
	(
		{
			"name" : "enb_mode_window",
			"type" : "window",
			"x" : 0,
			"y" : 5,
			"width":304,
			"height":SMALL_OPTION_HEIGHT,
			"children":
			(
				{
					"name" : "enb_mode_title_img",
					"type" : "expanded_image",
					"x" : 5,
					"y" : 0,
					"image" : IMG_DIR+"option_title.png",
					"children":
					(
						{
							"name" : "title_enb_mode",
							"type" : "text",
							"x" : TITLE_IMAGE_TEXT_X,
							"y" : TITLE_IMAGE_TEXT_Y,
							"text_horizontal_align":"left",
							"text" : uiScriptLocale.OPTION_ENB_MODE,
						},
					),
				},
				{
					"name" : "enbMode_on",
					"type" : "radio_button",
					"x" : OPTION_START_X+RADIO_BUTTON_RANGE_X*0,
					"y" : 33,
					"text" : uiScriptLocale.OPTION_ENB_MODE_ON,
					"text_x" : RADIO_BUTTON_TEXT_X,
					"tooltip_text" : uiScriptLocale.OPTION_ENB_MODE_ON_TOOLTIP,
					"default_image" : IMG_DIR + "radio_unselected.png",
					"over_image" : IMG_DIR + "radio_unselected.png",
					"down_image" : IMG_DIR + "radio_selected.png",
				},
				{
					"name" : "enbMode_off",
					"type" : "radio_button",
					"x" : OPTION_START_X+RADIO_BUTTON_RANGE_X*1,
					"y" : 33,
					"text" : uiScriptLocale.OPTION_ENB_MODE_OFF,
					"text_x" : RADIO_BUTTON_TEXT_X,
					"tooltip_text" : uiScriptLocale.OPTION_ENB_MODE_OFF_TOOLTIP,
					"default_image" : IMG_DIR + "radio_unselected.png",
					"over_image" : IMG_DIR + "radio_unselected.png",
					"down_image" : IMG_DIR + "radio_selected.png",
				},
			),
		},
		{
			"name" : "effect_level_window",
			"type" : "window",
			"x" : 0,
			"y" : SMALL_OPTION_HEIGHT+5,
			"width":304,
			"height":SMALL_OPTION_HEIGHT,
			"children":
			(
				{
					"name" : "effect_level_title_img",
					"type" : "expanded_image",
					"x" : 5,
					"y" : 0,
					"image" : IMG_DIR+"option_title.png",
					"children":
					(
						{
							"name" : "title_effect_level",
							"type" : "text",
							"x" : TITLE_IMAGE_TEXT_X,
							"y" : TITLE_IMAGE_TEXT_Y,
							"text_horizontal_align":"left",
							"text" : uiScriptLocale.GRAPHICONOFF_EFFECT_LEVEL,
						},
					),
				},
				{
					"name" : "effect_level1",
					"type" : "radio_button",
					"x" : OPTION_START_X+24*0,
					"y" : 33,
					"text" : uiScriptLocale.GRAPHICONOFF_EFFECT_LEVEL1,
					"text_x" : RADIO_BUTTON_TEXT_X,
					"tooltip_text" : uiScriptLocale.GRAPHICONOFF_EFFECT_LEVEL1_TOOLTIP,
					"default_image" : IMG_DIR + "radio_unselected.png",
					"over_image" : IMG_DIR + "radio_unselected.png",
					"down_image" : IMG_DIR + "radio_selected.png",
				},
				{
					"name" : "effect_level2",
					"type" : "radio_button",
					"x" : OPTION_START_X+24*1,
					"y" : 33,
					"text" : uiScriptLocale.GRAPHICONOFF_EFFECT_LEVEL2,
					"text_x" : RADIO_BUTTON_TEXT_X,
					"tooltip_text" : uiScriptLocale.GRAPHICONOFF_EFFECT_LEVEL2_TOOLTIP,
					"default_image" : IMG_DIR + "radio_unselected.png",
					"over_image" : IMG_DIR + "radio_unselected.png",
					"down_image" : IMG_DIR + "radio_selected.png",
				},
				{
					"name" : "effect_level3",
					"type" : "radio_button",
					"x" : OPTION_START_X+24*2,
					"y" : 33,
					"text" : uiScriptLocale.GRAPHICONOFF_EFFECT_LEVEL3,
					"text_x" : RADIO_BUTTON_TEXT_X,
					"tooltip_text" : uiScriptLocale.GRAPHICONOFF_EFFECT_LEVEL3_TOOLTIP,
					"default_image" : IMG_DIR + "radio_unselected.png",
					"over_image" : IMG_DIR + "radio_unselected.png",
					"down_image" : IMG_DIR + "radio_selected.png",
				},
				{
					"name" : "effect_level4",
					"type" : "radio_button",
					"x" : OPTION_START_X+24*3,
					"y" : 33,
					"text" : uiScriptLocale.GRAPHICONOFF_EFFECT_LEVEL4,
					"text_x" : RADIO_BUTTON_TEXT_X,
					"tooltip_text" : uiScriptLocale.GRAPHICONOFF_EFFECT_LEVEL4_TOOLTIP,
					"default_image" : IMG_DIR + "radio_unselected.png",
					"over_image" : IMG_DIR + "radio_unselected.png",
					"down_image" : IMG_DIR + "radio_selected.png",
				},
				{
					"name" : "effect_level5",
					"type" : "radio_button",
					"x" : OPTION_START_X+24*4,
					"y" : 33,
					"text" : uiScriptLocale.GRAPHICONOFF_EFFECT_LEVEL5,
					"text_x" : RADIO_BUTTON_TEXT_X,
					"tooltip_text" : uiScriptLocale.GRAPHICONOFF_EFFECT_LEVEL5_TOOLTIP,
					"default_image" : IMG_DIR + "radio_unselected.png",
					"over_image" : IMG_DIR + "radio_unselected.png",
					"down_image" : IMG_DIR + "radio_selected.png",
				},
				{
					"name" : "effect_apply",
					"type" : "button",
					"x" : 200,
					"y" : 33,
					"text" : uiScriptLocale.GRAPHICONOFF_EFFECT_APPLY,
					"default_image" : "d:/ymir work/ui/game/option/option_button_thin_norm.tga",
					"over_image" : "d:/ymir work/ui/game/option/option_button_thin_hover.tga",
					"down_image" : "d:/ymir work/ui/game/option/option_button_thin_down.tga",
				},
			),
		},
		{
			"name" : "privateShop_level_window",
			"type" : "window",
			"x" : 0,
			"y" : SMALL_OPTION_HEIGHT*2+5,
			"width":304,
			"height":SMALL_OPTION_HEIGHT,
			"children":
			(
				{
					"name" : "privateShop_level_title_img",
					"type" : "expanded_image",
					"x" : 5,
					"y" : 0,
					"image" : IMG_DIR+"option_title.png",
					"children":
					(
						{
							"name" : "title_privateShop_level",
							"type" : "text",
							"x" : TITLE_IMAGE_TEXT_X,
							"y" : TITLE_IMAGE_TEXT_Y,
							"text_horizontal_align":"left",
							"text" : uiScriptLocale.GRAPHICONOFF_PRIVATE_SHOP_LEVEL,
						},
					),
				},
				{
					"name" : "privateShop_level1",
					"type" : "radio_button",
					"x" : OPTION_START_X+24*0,
					"y" : 33,
					"text" : uiScriptLocale.GRAPHICONOFF_PRIVATE_SHOP_LEVEL1,
					"text_x" : RADIO_BUTTON_TEXT_X,
					"tooltip_text" : uiScriptLocale.GRAPHICONOFF_PRIVATE_SHOP_LEVEL1_TOOLTIP,
					"default_image" : IMG_DIR + "radio_unselected.png",
					"over_image" : IMG_DIR + "radio_unselected.png",
					"down_image" : IMG_DIR + "radio_selected.png",
				},
				{
					"name" : "privateShop_level2",
					"type" : "radio_button",
					"x" : OPTION_START_X+24*1,
					"y" : 33,
					"text" : uiScriptLocale.GRAPHICONOFF_PRIVATE_SHOP_LEVEL2,
					"text_x" : RADIO_BUTTON_TEXT_X,
					"tooltip_text" : uiScriptLocale.GRAPHICONOFF_PRIVATE_SHOP_LEVEL2_TOOLTIP,
					"default_image" : IMG_DIR + "radio_unselected.png",
					"over_image" : IMG_DIR + "radio_unselected.png",
					"down_image" : IMG_DIR + "radio_selected.png",
				},
				{
					"name" : "privateShop_level3",
					"type" : "radio_button",
					"x" : OPTION_START_X+24*2,
					"y" : 33,
					"text" : uiScriptLocale.GRAPHICONOFF_PRIVATE_SHOP_LEVEL3,
					"text_x" : RADIO_BUTTON_TEXT_X,
					"tooltip_text" : uiScriptLocale.GRAPHICONOFF_PRIVATE_SHOP_LEVEL3_TOOLTIP,
					"default_image" : IMG_DIR + "radio_unselected.png",
					"over_image" : IMG_DIR + "radio_unselected.png",
					"down_image" : IMG_DIR + "radio_selected.png",
				},
				{
					"name" : "privateShop_level4",
					"type" : "radio_button",
					"x" : OPTION_START_X+24*3,
					"y" : 33,
					"text" : uiScriptLocale.GRAPHICONOFF_PRIVATE_SHOP_LEVEL4,
					"text_x" : RADIO_BUTTON_TEXT_X,
					"tooltip_text" : uiScriptLocale.GRAPHICONOFF_PRIVATE_SHOP_LEVEL4_TOOLTIP,
					"default_image" : IMG_DIR + "radio_unselected.png",
					"over_image" : IMG_DIR + "radio_unselected.png",
					"down_image" : IMG_DIR + "radio_selected.png",
				},
				{
					"name" : "privateShop_level5",
					"type" : "radio_button",
					"x" : OPTION_START_X+24*4,
					"y" : 33,
					"text" : uiScriptLocale.GRAPHICONOFF_PRIVATE_SHOP_LEVEL5,
					"text_x" : RADIO_BUTTON_TEXT_X,
					"tooltip_text" : uiScriptLocale.GRAPHICONOFF_PRIVATE_SHOP_LEVEL5_TOOLTIP,
					"default_image" : IMG_DIR + "radio_unselected.png",
					"over_image" : IMG_DIR + "radio_unselected.png",
					"down_image" : IMG_DIR + "radio_selected.png",
				},
				{
					"name" : "privateShop_apply",
					"type" : "button",
					"x" : 200,
					"y" : 33,
					"text" : uiScriptLocale.GRAPHICONOFF_PRIVATE_SHOP_APPLY,
					"default_image" : "d:/ymir work/ui/game/option/option_button_thin_norm.tga",
					"over_image" : "d:/ymir work/ui/game/option/option_button_thin_hover.tga",
					"down_image" : "d:/ymir work/ui/game/option/option_button_thin_down.tga",
				},
			),
		},
		{
			"name" : "dropItem_level_window",
			"type" : "window",
			"x" : 0,
			"y" : SMALL_OPTION_HEIGHT*3+5,
			"width":304,
			"height":SMALL_OPTION_HEIGHT,
			"children":
			(
				{
					"name" : "dropItem_level_title_img",
					"type" : "expanded_image",
					"x" : 5,
					"y" : 0,
					"image" : IMG_DIR+"option_title.png",
					"children":
					(
						{
							"name" : "title_dropItem_level",
							"type" : "text",
							"x" : TITLE_IMAGE_TEXT_X,
							"y" : TITLE_IMAGE_TEXT_Y,
							"text_horizontal_align":"left",
							"text" : uiScriptLocale.GRAPHICONOFF_DROP_ITEM_LEVEL,
						},
					),
				},
				{
					"name" : "dropItem_level1",
					"type" : "radio_button",
					"x" : OPTION_START_X+24*0,
					"y" : 33,
					"text" : uiScriptLocale.GRAPHICONOFF_DROP_ITEM_LEVEL1,
					"text_x" : RADIO_BUTTON_TEXT_X,
					"tooltip_text" : uiScriptLocale.GRAPHICONOFF_DROP_ITEM_LEVEL1_TOOLTIP,
					"default_image" : IMG_DIR + "radio_unselected.png",
					"over_image" : IMG_DIR + "radio_unselected.png",
					"down_image" : IMG_DIR + "radio_selected.png",
				},
				{
					"name" : "dropItem_level2",
					"type" : "radio_button",
					"x" : OPTION_START_X+24*1,
					"y" : 33,
					"text" : uiScriptLocale.GRAPHICONOFF_DROP_ITEM_LEVEL2,
					"text_x" : RADIO_BUTTON_TEXT_X,
					"tooltip_text" : uiScriptLocale.GRAPHICONOFF_DROP_ITEM_LEVEL2_TOOLTIP,
					"default_image" : IMG_DIR + "radio_unselected.png",
					"over_image" : IMG_DIR + "radio_unselected.png",
					"down_image" : IMG_DIR + "radio_selected.png",
				},
				{
					"name" : "dropItem_level3",
					"type" : "radio_button",
					"x" : OPTION_START_X+24*2,
					"y" : 33,
					"text" : uiScriptLocale.GRAPHICONOFF_DROP_ITEM_LEVEL3,
					"text_x" : RADIO_BUTTON_TEXT_X,
					"tooltip_text" : uiScriptLocale.GRAPHICONOFF_DROP_ITEM_LEVEL3_TOOLTIP,
					"default_image" : IMG_DIR + "radio_unselected.png",
					"over_image" : IMG_DIR + "radio_unselected.png",
					"down_image" : IMG_DIR + "radio_selected.png",
				},
				{
					"name" : "dropItem_level4",
					"type" : "radio_button",
					"x" : OPTION_START_X+24*3,
					"y" : 33,
					"text" : uiScriptLocale.GRAPHICONOFF_DROP_ITEM_LEVEL4,
					"text_x" : RADIO_BUTTON_TEXT_X,
					"tooltip_text" : uiScriptLocale.GRAPHICONOFF_DROP_ITEM_LEVEL4_TOOLTIP,
					"default_image" : IMG_DIR + "radio_unselected.png",
					"over_image" : IMG_DIR + "radio_unselected.png",
					"down_image" : IMG_DIR + "radio_selected.png",
				},
				{
					"name" : "dropItem_level5",
					"type" : "radio_button",
					"x" : OPTION_START_X+24*4,
					"y" : 33,
					"text" : uiScriptLocale.GRAPHICONOFF_DROP_ITEM_LEVEL5,
					"text_x" : RADIO_BUTTON_TEXT_X,
					"tooltip_text" : uiScriptLocale.GRAPHICONOFF_DROP_ITEM_LEVEL5_TOOLTIP,
					"default_image" : IMG_DIR + "radio_unselected.png",
					"over_image" : IMG_DIR + "radio_unselected.png",
					"down_image" : IMG_DIR + "radio_selected.png",
				},
				{
					"name" : "dropItem_apply",
					"type" : "button",
					"x" : 200,
					"y" : 33,
					"text" : uiScriptLocale.GRAPHICONOFF_DROP_ITEM_APPLY,
					"default_image" : "d:/ymir work/ui/game/option/option_button_thin_norm.tga",
					"over_image" : "d:/ymir work/ui/game/option/option_button_thin_hover.tga",
					"down_image" : "d:/ymir work/ui/game/option/option_button_thin_down.tga",
				},
			),
		},
		{
			"name" : "pet_status_window",
			"type" : "window",
			"x" : 0,
			"y" : SMALL_OPTION_HEIGHT*4+5,
			"width":304,
			"height":SMALL_OPTION_HEIGHT,
			"children":
			(
				{
					"name" : "pet_status_title_img",
					"type" : "expanded_image",
					"x" : 5,
					"y" : 0,
					"image" : IMG_DIR+"option_title.png",
					"children":
					(
						{
							"name" : "title_pet_status",
							"type" : "text",
							"x" : TITLE_IMAGE_TEXT_X,
							"y" : TITLE_IMAGE_TEXT_Y,
							"text_horizontal_align":"left",
							"text" : uiScriptLocale.GRAPHICONOFF_PET_STATUS,
						},
					),
				},
				{
					"name" : "pet_on",
					"type" : "radio_button",
					"x" : OPTION_START_X+RADIO_BUTTON_RANGE_X*0,
					"y" : 33,
					"text" : uiScriptLocale.GRAPHICONOFF_PET_STATUS_ON,
					"text_x" : RADIO_BUTTON_TEXT_X,
					"tooltip_text" : uiScriptLocale.GRAPHICONOFF_PET_STATUS_ON_TOOLTIP,
					"default_image" : IMG_DIR + "radio_unselected.png",
					"over_image" : IMG_DIR + "radio_unselected.png",
					"down_image" : IMG_DIR + "radio_selected.png",
				},
				{
					"name" : "pet_off",
					"type" : "radio_button",
					"x" : OPTION_START_X+RADIO_BUTTON_RANGE_X*1,
					"y" : 33,
					"text" : uiScriptLocale.GRAPHICONOFF_PET_STATUS_OFF,
					"text_x" : RADIO_BUTTON_TEXT_X,
					"tooltip_text" : uiScriptLocale.GRAPHICONOFF_PET_STATUS_OFF_TOOLTIP,
					"default_image" : IMG_DIR + "radio_unselected.png",
					"over_image" : IMG_DIR + "radio_unselected.png",
					"down_image" : IMG_DIR + "radio_selected.png",
				},
			),
		},
		{
			"name" : "npcName_status_window",
			"type" : "window",
			"x" : 0,
			"y" : SMALL_OPTION_HEIGHT*5+5,
			"width":304,
			"height":SMALL_OPTION_HEIGHT,
			"children":
			(
				{
					"name" : "npcName_status_title_img",
					"type" : "expanded_image",
					"x" : 5,
					"y" : 0,
					"image" : IMG_DIR+"option_title.png",
					"children":
					(
						{
							"name" : "title_npcName_status",
							"type" : "text",
							"x" : TITLE_IMAGE_TEXT_X,
							"y" : TITLE_IMAGE_TEXT_Y,
							"text_horizontal_align":"left",
							"text" : uiScriptLocale.GRAPHICONOFF_NPC_NAME_STATUS,
						},
					),
				},
				{
					"name" : "npcName_on",
					"type" : "radio_button",
					"x" : OPTION_START_X+RADIO_BUTTON_RANGE_X*0,
					"y" : 33,
					"text" : uiScriptLocale.GRAPHICONOFF_NPC_NAME_STATUS_ON,
					"text_x" : RADIO_BUTTON_TEXT_X,
					"tooltip_text" : uiScriptLocale.GRAPHICONOFF_NPC_NAME_STATUS_ON_TOOLTIP,
					"default_image" : IMG_DIR + "radio_unselected.png",
					"over_image" : IMG_DIR + "radio_unselected.png",
					"down_image" : IMG_DIR + "radio_selected.png",
				},
				{
					"name" : "npcName_off",
					"type" : "radio_button",
					"x" : OPTION_START_X+RADIO_BUTTON_RANGE_X*1,
					"y" : 33,
					"text" : uiScriptLocale.GRAPHICONOFF_NPC_NAME_STATUS_OFF,
					"text_x" : RADIO_BUTTON_TEXT_X,
					"tooltip_text" : uiScriptLocale.GRAPHICONOFF_NPC_NAME_STATUS_OFF_TOOLTIP,
					"default_image" : IMG_DIR + "radio_unselected.png",
					"over_image" : IMG_DIR + "radio_unselected.png",
					"down_image" : IMG_DIR + "radio_selected.png",
				},
			),
		},
		{
			"name" : "show_mob_info_window",
			"type" : "window",
			"x" : 0,
			"y" : SMALL_OPTION_HEIGHT*6+5,
			"width":304,
			"height":SMALL_OPTION_HEIGHT,
			"exPos" : [0, SMALL_OPTION_HEIGHT*6+5],
			"children":
			(
				{
					"name" : "show_mob_info_title_img",
					"type" : "expanded_image",
					"x" : 5,
					"y" : 0,
					"image" : IMG_DIR+"option_title.png",
					"children":
					(
						{
							"name" : "title_show_mob_info",
							"type" : "text",
							"x" : TITLE_IMAGE_TEXT_X,
							"y" : TITLE_IMAGE_TEXT_Y,
							"text_horizontal_align":"left",
							"text" : uiScriptLocale.OPTION_MOB_INFO,
						},
					),
				},
				{
					"name" : "show_mob_level_button",
					"type" : "toggle_button",
					"x" : OPTION_START_X+RADIO_BUTTON_RANGE_X*0,
					"y" : 33,
					"text" : uiScriptLocale.OPTION_MOB_INFO_LEVEL,
					"text_x" : RADIO_BUTTON_TEXT_X,
					"default_image" : IMG_DIR + "toggle_unselected.png",
					"over_image" : IMG_DIR + "toggle_unselected.png",
					"down_image" : IMG_DIR + "toggle_selected.png",
				},
				{
					"name" : "show_mob_AI_flag_button",
					"type" : "toggle_button",
					"x" : OPTION_START_X+RADIO_BUTTON_RANGE_X*1,
					"y" : 33,
					"text" : uiScriptLocale.OPTION_MOB_INFO_AGGR,
					"text_x" : RADIO_BUTTON_TEXT_X,
					"default_image" : IMG_DIR + "toggle_unselected.png",
					"over_image" : IMG_DIR + "toggle_unselected.png",
					"down_image" : IMG_DIR + "toggle_selected.png",
				},
			),
		},
		{
			"name" : "fov_stone_scale_window",
			"type" : "window",
			"x" : 0,
			"y" : SMALL_OPTION_HEIGHT*7+5,
			"width":304,
			"height":SLIDER_OPTION_HEIGHT*2,
			"children":
			(
				{
					"name" : "fov_stone_scale_title_img",
					"type" : "expanded_image",
					"x" : 5,
					"y" : 0,
					"image" : IMG_DIR+"option_title.png",
					"children":
					(
						{
							"name" : "title_fov_stone_scale",
							"type" : "text",
							"x" : TITLE_IMAGE_TEXT_X,
							"y" : TITLE_IMAGE_TEXT_Y,
							"text_horizontal_align":"left",
							"text" : "Görüþ & Metin Taþlarý",
						},
					),
				},
				{
					"name" : "fov_text",
					"type" : "text",
					"text_horizontal_align":"left",
					"x" : OPTION_START_X,
					"y" : SLIDER_START_Y-20,
					"text":uiScriptLocale.OPTION_FOV,
					"color" : PRIMARY_COLOR,
				},
				{
					"name" : "fov_controller",
					"type" : "sliderbar_advancedgameoptions",
					"x" : OPTION_START_X,
					"y" : SLIDER_START_Y,
				},
				{
					"name" : "fov_reset_button",
					"type" : "button",
					"x" : 240,
					"y" : SLIDER_START_Y-2,
					"tooltip_text" : uiScriptLocale.OPTION_FOV_RESET,
					"default_image" : "d:/ymir work/ui/game/option/option_button_reset_norm.tga",
					"over_image" : "d:/ymir work/ui/game/option/option_button_reset_hover.tga",
					"down_image" : "d:/ymir work/ui/game/option/option_button_reset_down.tga",
				},
				{
					"name" : "stone_scale_text",
					"type" : "text",
					"text_horizontal_align":"left",
					"x" : OPTION_START_X,
					"y" : SLIDER_START_Y*2-20,
					"text":uiScriptLocale.OPTION_STONES,
					"color" : PRIMARY_COLOR,
				},
				{
					"name" : "stone_scale_controller",
					"type" : "sliderbar_advancedgameoptions",
					"x" : OPTION_START_X,
					"y" : SLIDER_START_Y*2,
				},
				{
					"name" : "stone_scale_reset_button",
					"type" : "button",
					"x" : 240,
					"y" : SLIDER_START_Y*2-2,
					"tooltip_text" : uiScriptLocale.OPTION_FOV_RESET,
					"default_image" : "d:/ymir work/ui/game/option/option_button_reset_norm.tga",
					"over_image" : "d:/ymir work/ui/game/option/option_button_reset_hover.tga",
					"down_image" : "d:/ymir work/ui/game/option/option_button_reset_down.tga",
				},
			),
		},
	),
}

