#ifndef __INC_AFFECT_H
#define __INC_AFFECT_H

class CAffect
{
	public:
		DWORD	dwType;
		BYTE    bApplyOn;
		long    lApplyValue;
		DWORD   dwFlag;
		long	lDuration;
		long	lSPCost;
#ifdef ENABLE_NINETH_SKILL
		uint8_t bShieldDuration;
#endif

		static CAffect* Acquire();
		static void Release(CAffect* p);
};

enum EAffectTypes
{
	AFFECT_NONE,
	AFFECT_MOV_SPEED = 200,
	AFFECT_ATT_SPEED,
	AFFECT_ATT_GRADE,
	AFFECT_INVISIBILITY,
	AFFECT_STR,
	AFFECT_DEX, // 205
	AFFECT_CON,
	AFFECT_INT,
	AFFECT_FISH_MIND_PILL,
	AFFECT_POISON,
	AFFECT_STUN, // 210
	AFFECT_SLOW,
	AFFECT_DUNGEON_READY,
	AFFECT_DUNGEON_UNIQUE,
	AFFECT_BUILDING,
	AFFECT_REVIVE_INVISIBLE, // 215
	AFFECT_FIRE,
	AFFECT_CAST_SPEED,
	AFFECT_HP_RECOVER_CONTINUE,
	AFFECT_SP_RECOVER_CONTINUE,
	AFFECT_POLYMORPH, // 220
	AFFECT_MOUNT,
	AFFECT_WAR_FLAG, // 222
	AFFECT_BLOCK_CHAT, // 223
	AFFECT_CHINA_FIREWORK,
	AFFECT_BOW_DISTANCE, // 225
	AFFECT_DEF_GRADE, // 226
#ifdef __ENABLE_COLLECTIONS_SYSTEM__
	AFFECT_COLLECTIONS0 = 303,
	AFFECT_COLLECTIONS1 = 304,
	AFFECT_COLLECTIONS2 = 305,
	AFFECT_COLLECTIONS3 = 306,
	AFFECT_COLLECTIONS4 = 307,
	AFFECT_COLLECTIONS5 = 308,
	AFFECT_COLLECTIONS6 = 309,
#endif
#ifdef ENABLE_COLLECT_WINDOW
	AFFECT_COLLECT_BIOLOG = 310,
	AFFECT_COLLECT_KOLEKCJONER = 311,
	AFFECT_COLLECT_POLOWANIE = 312,
	AFFECT_COLLECT_BOSSOLOGIA = 313,
	AFFECT_COLLECT_METINOLOGIA = 314,
	AFFECT_COLLECT_KOLEKCJONER_EXTRA = 315,
#endif

	AFFECT_PREMIUM_START = 500,
	AFFECT_EXP_BONUS = 500,
	AFFECT_ITEM_BONUS = 501,
	AFFECT_SAFEBOX = 502, // PREMIUM_SAFEBOX,
	AFFECT_AUTOLOOT = 503, // PREMIUM_AUTOLOOT,
	AFFECT_FISH_MIND = 504, // PREMIUM_FISH_MIND,
	AFFECT_MARRIAGE_FAST = 505,
	AFFECT_GOLD_BONUS = 506,
	AFFECT_PREMIUM_END = 509,//whats teh affect id

	AFFECT_MALL = 510,
	AFFECT_NO_DEATH_PENALTY = 511,
	AFFECT_SKILL_BOOK_BONUS = 512,
	AFFECT_SKILL_NO_BOOK_DELAY = 513,
	AFFECT_HAIR = 514,
	AFFECT_COLLECT = 515,
	AFFECT_EXP_BONUS_EURO_FREE = 516,
	AFFECT_EXP_BONUS_EURO_FREE_UNDER_15 = 517,
	AFFECT_UNIQUE_ABILITY = 518,

	AFFECT_CUBE_1,
	AFFECT_CUBE_2,
	AFFECT_CUBE_3,
	AFFECT_CUBE_4,
	AFFECT_CUBE_5,
	AFFECT_CUBE_6,
	AFFECT_CUBE_7,
	AFFECT_CUBE_8,
	AFFECT_CUBE_9,
	AFFECT_CUBE_10,
	AFFECT_CUBE_11,
	AFFECT_CUBE_12,
	AFFECT_HORSE_NAME,
	AFFECT_MOUNT_BONUS,
	AFFECT_AUTO_HP_RECOVERY = 534,
	AFFECT_AUTO_SP_RECOVERY = 535,
	AFFECT_DRAGON_SOUL_QUALIFIED = 540,
	AFFECT_DRAGON_SOUL_DECK_0 = 541,
	AFFECT_DRAGON_SOUL_DECK_1 = 542,

#ifdef ENABLE_GROWTH_PET_SYSTEM
	AFFECT_GROWTH_PET = 544,
#endif

#ifdef ENABLE_BIOLOGIST_SYSTEM
	AFFECT_BIO 			= 545,
	AFFECT_BIO_92 		= 546,
	AFFECT_BIO_94 		= 547,
#endif

	AFFECT_RAMADAN_ABILITY = 300,
	AFFECT_RAMADAN_RING = 301,
	AFFECT_NOG_ABILITY = 302,
	AFFECT_HOLLY_STONE_POWER = 303,

#ifdef ENABLE_RENEWAL_AFFECT
	AFFECT_BLEND = 548,
	AFFECT_MALL_PLUS = 549,
	AFFECT_BLEND_PLUS = 550,
#endif

#ifdef ENABLE_ATTENDANCE_EVENT
	AFFECT_EXP_BONUS_EVENT = 557,
	AFFECT_ATT_SPEED_SLOW = 558,
#endif

#ifdef ENABLE_PET_SYSTEM
	AFFECT_PET_SUMMON = 564,
#endif
#ifdef ENABLE_BATTLE_PASS
	AFFECT_BATTLE_BONUS1 = 574,
	AFFECT_BATTLE_BONUS2 = 575,
	AFFECT_BATTLE_BONUS3 = 576,
#endif
#ifdef ENABLE_EQUIPMENT_HAND_EFFECT
	AFFECT_DBONE_BRONZE = 590,
	AFFECT_DBONE_SILVER = 591,
#endif
#ifdef ENABLE_EQUIPMENT_HAND_EFFECT
	AFFECT_DBONE_GOLD = 602,
	AFFECT_DBONE_DIAMOND = 603,
	AFFECT_DBONE_PLATIN = 604,
	AFFECT_DBONE_EMERALD = 605,
#endif
#ifdef ENABLE_MELEY_LAIR_DUNGEON
	AFFECT_STATUE = 700,
#endif
#ifdef ENABLE_RENEWAL_OFFLINESHOP
	AFFECT_DECORATION = 703,
#endif
#ifdef ENABLE_MULTI_FARM_BLOCK
	AFFECT_MULTI_FARM_PREMIUM = 704,
#endif

#ifdef ENABLE_AUTOMATIC_PICK_UP_SYSTEM
	AFFECT_AUTO_PICK_UP = 706,
#endif

#ifdef ENABLE_PASSIVE_SYSTEM
	AFFECT_PASSIVE_RELIC_STONE_DEF = 707,
	AFFECT_PASSIVE_RELIC_DISMOUNT_SPEED = 708,
#endif

#ifdef ENABLE_QUEEN_NETHIS
	AFFECT_SUNGMA_MOVE_DEBUFF = 815,
	AFFECT_SUNGMA_STR_DEBUFF = 816,
#endif

#ifdef __AUTO_HUNT__
	AFFECT_AUTO_HUNT =830,
	AFFECT_AUTO_HUNT_AFFECT =831,
#endif
#ifdef ENABLE_SUNG_MAHI_TOWER
	AFFECT_SUNG_MAHI_BP,
	AFFECT_SUNG_MAHI_CURSE,
#endif

#ifdef __LEADERSHIP__BONUS__
	AFF_LEADERSHIP = 901,
#endif

#ifdef ENABLE_CONQUEROR_LEVEL
	AFFECT_SUNGMA_STR	= 907,
	AFFECT_SUNGMA_HP	= 908,
	AFFECT_SUNGMA_MOVE	= 909,
	AFFECT_SUNGMA_IMMUNE	= 910,
#endif
	AFFECT_QUEST_START_IDX = 1000
};

enum EAffectBits
{
	AFF_NONE,						// 0	- Binary
	AFF_YMIR,						// 1	- 0
	AFF_INVISIBILITY,				// 2	- 1
	AFF_SPAWN,						// 3	- 2
	AFF_POISON,						// 4	- 3
	AFF_SLOW,						// 5	- 4
	AFF_STUN,						// 6	- 5
	AFF_DUNGEON_READY,				// 7	- 6
	AFF_DUNGEON_UNIQUE,				// 8	- 7
	AFF_BUILDING_CONSTRUCTION_SMALL,// 9	- 8
	AFF_BUILDING_CONSTRUCTION_LARGE,// 10	- 9
	AFF_BUILDING_UPGRADE,			// 11	- 10
	AFF_MOV_SPEED_POTION,			// 12	- 11
	AFF_ATT_SPEED_POTION,			// 13	- 12
	AFF_FISH_MIND,					// 14	- 13
	AFF_JEONGWIHON,					// 15	- 14
	AFF_GEOMGYEONG,					// 16	- 15
	AFF_CHEONGEUN,					// 17	- 16
	AFF_GYEONGGONG,					// 18	- 17
	AFF_EUNHYUNG,					// 19	- 18
	AFF_GWIGUM,						// 20	- 19
	AFF_TERROR,						// 21	- 20
	AFF_JUMAGAP,					// 22	- 21
	AFF_HOSIN,						// 23	- 22
	AFF_BOHO,						// 24	- 23
	AFF_KWAESOK,					// 25	- 24
	AFF_MANASHIELD,					// 26	- 25
	AFF_MUYEONG,					// 27	- 26
	AFF_REVIVE_INVISIBLE,			// 28	- 27
	AFF_FIRE,						// 29	- 28
	AFF_GICHEON,					// 30	- 29
	AFF_JEUNGRYEOK,					// 31	- 30
	AFF_TANHWAN_DASH,				// 32	- 31
	AFF_PABEOP,						// 33	- 32
	AFF_CHEONGEUN_WITH_FALL,		// 34	- 33
	AFF_POLYMORPH,					// 35	- 34
	AFF_WAR_FLAG1,					// 36	- 35
	AFF_WAR_FLAG2,					// 37	- 36
	AFF_WAR_FLAG3,					// 38	- 37
	AFF_CHINA_FIREWORK,				// 39	- 38
	AFF_HAIR,						// 40	- 39
	AFF_GERMANY,					// 41	- 40
	AFF_DS,							// 42	- 41
#ifdef ENABLE_RENEWAL_TEAM_AFFECT
	AFF_TEAM_SA,					// 43	- 42
	AFF_TEAM_GA,					// 44	- 43
	AFF_TEAM_GM,					// 45	- 44
	AFF_TEAM_TGM,					// 46	- 47
#endif
#ifdef __AUTO_HUNT__
	AFF_AUTO_HUNT,					// 48	- 49
#endif
#ifdef ENABLE_MELEY_LAIR_DUNGEON
	AFF_STATUE1,					// 49	- 50
	AFF_STATUE2,					// 50	- 51
	AFF_STATUE3,					// 51	- 52
	AFF_STATUE4,					// 52	- 53
#endif
#ifdef ENABLE_EQUIPMENT_HAND_EFFECT
	AFF_DBONE_BRONZE,				// 53	- 54
	AFF_DBONE_SILVER,				// 54	- 55
	AFF_DBONE_GOLD,					// 55	- 56
	AFF_DBONE_DIAMOND,				// 56	- 57
	AFF_DBONE_PLATIN,				// 57	- 58
	AFF_DBONE_EMERALD,				// 58	- 59
#endif
#ifdef ENABLE_NINETH_SKILL
	AFF_CHEONUN,					// 62	- 61
	AFF_CHUNWOON_MOOJUK,			// 63	- 62
#endif

	AFF_BITS_MAX
};

extern void SendAffectAddPacket(LPDESC d, CAffect * pkAff);

// AFFECT_DURATION_BUG_FIX
enum AffectVariable
{
	// Affect sonsuz olacaðý zaman kullan.
	// Sürekli zaman azalttýðý için sonsuzluðu çok büyük bir deðerle taklit et.
	//// 24 bit küçük kaldýðý için 25 bit kullanýlýr.
	// ... 25 bit dendiði halde yorum satýrlarýnda 29 bit kullanýldýðý söyleniyor...
	// Collect quest’te sonsuz süreyi 60 yýl olarak kullandýðýmýzdan, burada da 60 yýl yapalým.

	INFINITE_AFFECT_DURATION = 60*60*24*365*60
};
// END_AFFECT_DURATION_BUG_FIX

#endif
